star_wars = {'Luke Skywalker': {'characteristics': ('Human', 'male', '172.0', '77.0'),
  'homeworld': 'Tatooine',
  'films': ['The Empire Strikes Back',
   'Revenge of the Sith',
   'Return of the Jedi',
   'A New Hope',
   'The Force Awakens']},
 'C-3PO': {'characteristics': ('Droid', 'none', '167.0', '75.0'),
  'homeworld': 'Tatooine',
  'films': ['The Empire Strikes Back',
   'Attack of the Clones',
   'The Phantom Menace',
   'Revenge of the Sith',
   'Return of the Jedi',
   'A New Hope']},
 'R2-D2': {'characteristics': ('Droid', 'none', '96.0', '32.0'),
  'homeworld': 'Naboo',
  'films': ['The Empire Strikes Back',
   'Attack of the Clones',
   'The Phantom Menace',
   'Revenge of the Sith',
   'Return of the Jedi',
   'A New Hope',
   'The Force Awakens']},
 'Darth Vader': {'characteristics': ('Human', 'male', '202.0', '136.0'),
  'homeworld': 'Tatooine',
  'films': ['The Empire Strikes Back',
   'Revenge of the Sith',
   'Return of the Jedi',
   'A New Hope']},
 'Leia Organa': {'characteristics': ('Human', 'female', '150.0', '49.0'),
  'homeworld': 'Alderaan',
  'films': ['The Empire Strikes Back',
   'Revenge of the Sith',
   'Return of the Jedi',
   'A New Hope',
   'The Force Awakens']},
 'Owen Lars': {'characteristics': ('Human', 'male', '178.0', '120.0'),
  'homeworld': 'Tatooine',
  'films': ['Attack of the Clones', 'Revenge of the Sith', 'A New Hope']},
 'Beru Whitesun lars': {'characteristics': ('Human',
   'female',
   '165.0',
   '75.0'),
  'homeworld': 'Tatooine',
  'films': ['Attack of the Clones', 'Revenge of the Sith', 'A New Hope']},
 'R5-D4': {'characteristics': ('Droid', 'none', '97.0', '32.0'),
  'homeworld': 'Tatooine',
  'films': ['A New Hope']},
 'Biggs Darklighter': {'characteristics': ('Human', 'male', '183.0', '84.0'),
  'homeworld': 'Tatooine',
  'films': ['A New Hope']},
 'Obi-Wan Kenobi': {'characteristics': ('Human', 'male', '182.0', '77.0'),
  'homeworld': 'Stewjon',
  'films': ['The Empire Strikes Back',
   'Attack of the Clones',
   'The Phantom Menace',
   'Revenge of the Sith',
   'Return of the Jedi',
   'A New Hope']},
 'Anakin Skywalker': {'characteristics': ('Human', 'male', '188.0', '84.0'),
  'homeworld': 'Tatooine',
  'films': ['Attack of the Clones',
   'The Phantom Menace',
   'Revenge of the Sith']},
 'Chewbacca': {'characteristics': ('Wookiee', 'male', '228.0', '112.0'),
  'homeworld': 'Kashyyyk',
  'films': ['The Empire Strikes Back',
   'Revenge of the Sith',
   'Return of the Jedi',
   'A New Hope',
   'The Force Awakens']},
 'Han Solo': {'characteristics': ('Human', 'male', '180.0', '80.0'),
  'homeworld': 'Corellia',
  'films': ['The Empire Strikes Back',
   'Return of the Jedi',
   'A New Hope',
   'The Force Awakens']},
 'Greedo': {'characteristics': ('Rodian', 'male', '173.0', '74.0'),
  'homeworld': 'Rodia',
  'films': ['A New Hope']},
 'Jabba Desilijic Tiure': {'characteristics': ('Hutt',
   'hermaphroditic',
   '175.0',
   '1358.0'),
  'homeworld': 'Nal Hutta',
  'films': ['The Phantom Menace', 'Return of the Jedi', 'A New Hope']},
 'Wedge Antilles': {'characteristics': ('Human', 'male', '170.0', '77.0'),
  'homeworld': 'Corellia',
  'films': ['The Empire Strikes Back', 'Return of the Jedi', 'A New Hope']},
 'Jek Tono Porkins': {'characteristics': ('Human', 'male', '180.0', '110.0'),
  'homeworld': 'Bestine IV',
  'films': ['A New Hope']},
 'Palpatine': {'characteristics': ('Human', 'male', '170.0', '75.0'),
  'homeworld': 'Naboo',
  'films': ['The Empire Strikes Back',
   'Attack of the Clones',
   'The Phantom Menace',
   'Revenge of the Sith',
   'Return of the Jedi']},
 'Boba Fett': {'characteristics': ('Human', 'male', '183.0', '78.2'),
  'homeworld': 'Kamino',
  'films': ['The Empire Strikes Back',
   'Attack of the Clones',
   'Return of the Jedi']},
 'Bossk': {'characteristics': ('Trandoshan', 'male', '190.0', '113.0'),
  'homeworld': 'Trandosha',
  'films': ['The Empire Strikes Back']},
 'Lando Calrissian': {'characteristics': ('Human', 'male', '177.0', '79.0'),
  'homeworld': 'Socorro',
  'films': ['The Empire Strikes Back', 'Return of the Jedi']},
 'Lobot': {'characteristics': ('Human', 'male', '175.0', '79.0'),
  'homeworld': 'Bespin',
  'films': ['The Empire Strikes Back']},
 'Ackbar': {'characteristics': ('Mon Calamari', 'male', '180.0', '83.0'),
  'homeworld': 'Mon Cala',
  'films': ['Return of the Jedi', 'The Force Awakens']},
 'Wicket Systri Warrick': {'characteristics': ('Ewok', 'male', '88.0', '20.0'),
  'homeworld': 'Endor',
  'films': ['Return of the Jedi']},
 'Nien Nunb': {'characteristics': ('Sullustan', 'male', '160.0', '68.0'),
  'homeworld': 'Sullust',
  'films': ['Return of the Jedi']},
 'Nute Gunray': {'characteristics': ('Neimodian', 'male', '191.0', '90.0'),
  'homeworld': 'Cato Neimoidia',
  'films': ['Attack of the Clones',
   'The Phantom Menace',
   'Revenge of the Sith']},
 'Jar Jar Binks': {'characteristics': ('Gungan', 'male', '196.0', '66.0'),
  'homeworld': 'Naboo',
  'films': ['Attack of the Clones', 'The Phantom Menace']},
 'Roos Tarpals': {'characteristics': ('Gungan', 'male', '224.0', '82.0'),
  'homeworld': 'Naboo',
  'films': ['The Phantom Menace']},
 'Sebulba': {'characteristics': ('Dug', 'male', '112.0', '40.0'),
  'homeworld': 'Malastare',
  'films': ['The Phantom Menace']},
 'Darth Maul': {'characteristics': ('Zabrak', 'male', '175.0', '80.0'),
  'homeworld': 'Dathomir',
  'films': ['The Phantom Menace']},
 'Ayla Secura': {'characteristics': ("Twi'lek", 'female', '178.0', '55.0'),
  'homeworld': 'Ryloth',
  'films': ['Attack of the Clones',
   'The Phantom Menace',
   'Revenge of the Sith']},
 'Dud Bolt': {'characteristics': ('Vulptereen', 'male', '94.0', '45.0'),
  'homeworld': 'Vulpter',
  'films': ['The Phantom Menace']},
 'Ben Quadinaros': {'characteristics': ('Toong', 'male', '163.0', '65.0'),
  'homeworld': 'Tund',
  'films': ['The Phantom Menace']},
 'Mace Windu': {'characteristics': ('Human', 'male', '188.0', '84.0'),
  'homeworld': 'Haruun Kal',
  'films': ['Attack of the Clones',
   'The Phantom Menace',
   'Revenge of the Sith']},
 'Ki-Adi-Mundi': {'characteristics': ('Cerean', 'male', '198.0', '82.0'),
  'homeworld': 'Cerea',
  'films': ['Attack of the Clones',
   'The Phantom Menace',
   'Revenge of the Sith']},
 'Kit Fisto': {'characteristics': ('Nautolan', 'male', '196.0', '87.0'),
  'homeworld': 'Glee Anselm',
  'films': ['Attack of the Clones',
   'The Phantom Menace',
   'Revenge of the Sith']},
 'Adi Gallia': {'characteristics': ('Tholothian', 'female', '184.0', '50.0'),
  'homeworld': 'Coruscant',
  'films': ['The Phantom Menace', 'Revenge of the Sith']},
 'Plo Koon': {'characteristics': ('Kel Dor', 'male', '188.0', '80.0'),
  'homeworld': 'Dorin',
  'films': ['Attack of the Clones',
   'The Phantom Menace',
   'Revenge of the Sith']},
 'Gregar Typho': {'characteristics': ('Human', 'male', '185.0', '85.0'),
  'homeworld': 'Naboo',
  'films': ['Attack of the Clones']},
 'Poggle the Lesser': {'characteristics': ('Geonosian',
   'male',
   '183.0',
   '80.0'),
  'homeworld': 'Geonosis',
  'films': ['Attack of the Clones', 'Revenge of the Sith']},
 'Luminara Unduli': {'characteristics': ('Mirialan',
   'female',
   '170.0',
   '56.2'),
  'homeworld': 'Mirial',
  'films': ['Attack of the Clones', 'Revenge of the Sith']},
 'Barriss Offee': {'characteristics': ('Mirialan', 'female', '166.0', '50.0'),
  'homeworld': 'Mirial',
  'films': ['Attack of the Clones']},
 'Dooku': {'characteristics': ('Human', 'male', '193.0', '80.0'),
  'homeworld': 'Serenno',
  'films': ['Attack of the Clones', 'Revenge of the Sith']},
 'Jango Fett': {'characteristics': ('Human', 'male', '183.0', '79.0'),
  'homeworld': 'Concord Dawn',
  'films': ['Attack of the Clones']},
 'Zam Wesell': {'characteristics': ('Clawdite', 'female', '168.0', '55.0'),
  'homeworld': 'Zolan',
  'films': ['Attack of the Clones']},
 'Dexter Jettster': {'characteristics': ('Besalisk', 'male', '198.0', '102.0'),
  'homeworld': 'Ojom',
  'films': ['Attack of the Clones']},
 'Lama Su': {'characteristics': ('Kaminoan', 'male', '229.0', '88.0'),
  'homeworld': 'Kamino',
  'films': ['Attack of the Clones']},
 'Ratts Tyerell': {'characteristics': ('Aleena', 'male', '79.0', '15.0'),
  'homeworld': 'Aleen Minor',
  'films': ['The Phantom Menace']},
 'Wat Tambor': {'characteristics': ('Skakoan', 'male', '193.0', '48.0'),
  'homeworld': 'Skako',
  'films': ['Attack of the Clones']},
 'Shaak Ti': {'characteristics': ('Togruta', 'female', '178.0', '57.0'),
  'homeworld': 'Shili',
  'films': ['Attack of the Clones', 'Revenge of the Sith']},
 'Grievous': {'characteristics': ('Kaleesh', 'male', '216.0', '159.0'),
  'homeworld': 'Kalee',
  'films': ['Revenge of the Sith']},
 'Tarfful': {'characteristics': ('Wookiee', 'male', '234.0', '136.0'),
  'homeworld': 'Kashyyyk',
  'films': ['Revenge of the Sith']},
 'Raymus Antilles': {'characteristics': ('Human', 'male', '188.0', '79.0'),
  'homeworld': 'Alderaan',
  'films': ['Revenge of the Sith', 'A New Hope']},
 'Tion Medon': {'characteristics': ("Pau'an", 'male', '206.0', '80.0'),
  'homeworld': 'Utapau',
  'films': ['Revenge of the Sith']},
 'Padme Amidala': {'characteristics': ('Human', 'female', '165.0', '45.0'),
  'homeworld': 'Naboo',
  'films': ['Attack of the Clones',
   'The Phantom Menace',
   'Revenge of the Sith']}}