DATA_FILE = "data.csv"

READ = [
    ['Titanic', 'romance', 1997, 194.02],
    ['Matrix', 'scifi', 1993, 136.2],
    ['WALL-E', 'scifi', 2008, 98.65],
    ['Men in Black', 'scifi', 1997, 98.1],
    ['A Beautiful Mind', 'drama', 2001, 135.67],
    ['Star Trek Nemesis', 'scifi', 2002, 116.55],
    ['The godfather', 'drama', 1972, 175.3],
    ['Pirates of the Carribean: Black Pearl', 'adventure', 2003, 143.93],
    ['Sex and the City', 'romance', 2008, 145.73],
    ['Harry Potter and the Deathly Hallows 2', 'adventure', 2011, 130.85],
    ['Life of Brian', 'comedy', 1979, 94.1],
    ['Pulp Fiction', 'drama', 1994, 154.42],
    ['Alien', 'scifi', 1979, 116.47],
    ['Petelinji zajtrk', 'romance', 2007, 124.35],
    ['Rocky', 'drama', 1976, 120.12],
    ['American Pie', 'comedy', 1999, 95.78],
    ["Schindler's List", 'drama', 1993, 195.33],
    ['Ice Age: Dawn of the Dinosaurs', 'adventure', 2009, 94.93]
]

GENRES = {
    'romance': 154.7,
    'scifi': 113.19,
    'comedy': 94.94,
    'drama': 156.17,
    'adventure': 123.24,
}

RATINGS = {
    'deki': [4, 5, 0, 4, 0, 0, 4, 3, 1, 1, 0, 4, 0, 0, 3, 3, 5, 3],
    'Janez': [0, 3, 4, 4, 3, 0, 5, 5, 2, 4, 5, 3, 0, 3, 2, 2, 0, 5],
    'Rak': [3, 5, 0, 4, 0, 2, 0, 0, 2, 4, 0, 0, 0, 0, 3, 5, 0, 0],
    'ATom': [4, 5, 5, 5, 5, 3, 5, 5, 0, 0, 5, 0, 4, 0, 0, 1, 5, 4],
    'ivek': [3, 5, 5, 4, 2, 4, 3, 4, 1, 1, 0, 0, 4, 3, 3, 5, 2, 4],
    'miso': [3, 5, 4, 0, 4, 0, 0, 5, 2, 5, 0, 0, 3, 0, 5, 4, 0, 4],
    'ziga': [3, 3, 0, 2, 4, 0, 5, 2, 0, 0, 0, 5, 0, 2, 2, 2, 0, 2],
    'nepoznalec': [4, 0, 4, 4, 0, 0, 0, 3, 1, 3, 0, 0, 0, 4, 3, 3, 0, 3],
    'mx': [3, 5, 0, 4, 4, 4, 5, 2, 1, 1, 5, 5, 2, 0, 3, 1, 5, 1],
    'blazb': [5, 3, 5, 3, 0, 0, 4, 3, 1, 4, 3, 0, 0, 0, 0, 3, 4, 4],
    'jure': [4, 0, 0, 2, 0, 0, 0, 4, 0, 4, 0, 0, 3, 2, 3, 2, 4, 4],
    'saso': [3, 5, 0, 5, 0, 0, 0, 4, 0, 5, 0, 4, 4, 0, 4, 3, 5, 0],
    'Vida': [3, 2, 5, 4, 0, 0, 2, 0, 3, 0, 0, 0, 0, 1, 2, 1, 4, 5],
    'sasha': [3, 0, 0, 0, 0, 3, 0, 0, 2, 0, 5, 0, 4, 0, 4, 0, 0, 3],
    'majcn': [5, 4, 0, 2, 0, 0, 0, 5, 0, 5, 0, 0, 0, 1, 0, 3, 0, 5],
    'zidar': [1, 3, 5, 3, 5, 4, 0, 2, 0, 1, 0, 5, 5, 0, 2, 1, 1, 5],
    'mrbean': [3, 3, 2, 3, 5, 4, 4, 3, 0, 1, 0, 4, 0, 2, 1, 3, 0, 4],
    'zm12345': [4, 4, 2, 2, 5, 2, 5, 3, 0, 2, 3, 4, 2, 4, 0, 0, 5, 0],
    'HairyFotr': [0, 5, 5, 4, 5, 0, 0, 2, 0, 3, 5, 4, 5, 0, 3, 0, 0, 0],
    'Duco': [3, 5, 0, 3, 4, 0, 5, 2, 0, 2, 4, 5, 5, 0, 3, 2, 4, 0],
    'Slovenc': [3, 4, 3, 4, 4, 3, 0, 4, 1, 3, 0, 0, 0, 4, 3, 2, 3, 3],
    'HIP_HOP': [5, 5, 4, 4, 5, 4, 5, 5, 0, 0, 0, 5, 4, 5, 3, 3, 4, 5],
    'X': [2, 5, 3, 4, 5, 5, 5, 2, 2, 3, 0, 0, 4, 0, 0, 4, 5, 3],
    'Karlos': [5, 5, 4, 4, 5, 0, 0, 5, 0, 0, 0, 0, 2, 4, 5, 3, 0, 2],
    'smotko': [3, 4, 5, 4, 5, 0, 4, 3, 1, 0, 0, 5, 4, 3, 0, 1, 5, 1],
    'abcd': [3, 3, 0, 4, 0, 0, 0, 4, 4, 0, 0, 0, 0, 0, 0, 2, 0, 4],
    'anika': [4, 0, 0, 3, 4, 0, 2, 5, 1, 0, 4, 2, 3, 4, 5, 3, 4, 5],
    'Vatreni': [4, 5, 5, 3, 5, 0, 5, 4, 0, 0, 5, 0, 4, 3, 3, 3, 5, 3],
    'Student n': [0, 5, 0, 3, 4, 0, 0, 0, 0, 0, 5, 0, 3, 2, 0, 2, 0, 0],
    'ddrrt': [4, 5, 4, 3, 3, 0, 2, 4, 0, 0, 4, 5, 5, 0, 3, 0, 4, 3],
    'ThePav': [3, 5, 5, 4, 0, 0, 5, 5, 0, 4, 4, 0, 4, 0, 0, 0, 5, 3],
    'klobasa': [3, 4, 5, 3, 0, 0, 5, 5, 0, 0, 0, 5, 4, 0, 0, 3, 5, 4],
    'kiwi': [4, 5, 0, 4, 0, 0, 5, 3, 0, 4, 0, 5, 0, 0, 0, 2, 5, 4],
    'seven': [5, 5, 5, 4, 4, 3, 5, 4, 2, 3, 5, 5, 5, 4, 4, 5, 4, 3],
    'gupi': [3, 0, 0, 2, 5, 0, 5, 3, 3, 0, 0, 0, 0, 4, 3, 3, 5, 4],
    'Ish': [5, 0, 0, 0, 2, 0, 0, 5, 3, 5, 3, 0, 0, 1, 0, 0, 0, 3],
    'Benjamin': [4, 5, 0, 4, 5, 0, 5, 3, 0, 5, 0, 5, 0, 4, 5, 3, 5, 4],
    'marko': [4, 5, 3, 3, 5, 4, 4, 4, 1, 3, 0, 5, 5, 0, 4, 2, 5, 3],
    'Batman': [3, 5, 4, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 3, 0, 3],
    'Andrej': [3, 5, 5, 0, 5, 0, 5, 5, 0, 5, 4, 0, 5, 0, 0, 0, 0, 4],
    'patriotka': [3, 3, 2, 2, 4, 0, 5, 4, 0, 3, 0, 5, 0, 3, 2, 4, 5, 4],
    'swizec': [5, 4, 5, 4, 5, 0, 3, 5, 0, 0, 5, 2, 5, 0, 4, 3, 4, 0],
    "LorD_D'DooM": [2, 3, 5, 1, 0, 4, 5, 3, 0, 1, 0, 5, 5, 0, 0, 1, 5, 4],
    'dwww': [3, 4, 3, 4, 4, 2, 3, 2, 1, 1, 3, 4, 4, 1, 3, 2, 5, 4],
    'shroomz': [3, 5, 5, 5, 0, 0, 5, 4, 2, 4, 5, 5, 0, 1, 2, 3, 5, 4],
    'MC': [3, 4, 4, 2, 5, 0, 5, 5, 0, 2, 0, 5, 4, 0, 4, 1, 0, 2],
    'voter007': [3, 4, 0, 5, 0, 0, 0, 5, 0, 3, 5, 0, 0, 1, 5, 4, 0, 5],
    'Voter003': [0, 3, 3, 4, 0, 0, 3, 5, 0, 2, 0, 3, 0, 4, 0, 4, 0, 5],
    'sedmica': [3, 3, 5, 4, 4, 0, 0, 4, 2, 4, 0, 0, 3, 4, 1, 5, 0, 3],
    'uawe': [3, 5, 0, 2, 4, 0, 5, 0, 1, 3, 4, 5, 3, 3, 4, 2, 4, 0],
    'lotus': [2, 5, 4, 5, 4, 3, 4, 4, 1, 3, 0, 5, 1, 5, 3, 4, 5, 4],
    'agent007': [4, 5, 3, 4, 4, 0, 0, 5, 0, 3, 0, 0, 0, 4, 5, 4, 3, 5],
    'Klemen K': [5, 5, 2, 3, 3, 0, 5, 2, 1, 1, 0, 5, 5, 2, 2, 4, 5, 2],
    'bq': [2, 4, 2, 0, 3, 0, 5, 3, 0, 3, 0, 5, 4, 3, 0, 1, 5, 2],
    'motika': [0, 5, 3, 5, 0, 0, 0, 3, 0, 2, 0, 2, 5, 0, 0, 4, 0, 3],
    'ad': [4, 4, 0, 4, 3, 0, 3, 5, 2, 0, 4, 4, 0, 3, 3, 4, 0, 4],
    'Haris': [3, 5, 4, 4, 4, 0, 0, 5, 2, 5, 0, 3, 3, 0, 4, 3, 4, 3],
    'Rdelca Kapica': [4, 5, 5, 5, 0, 0, 4, 5, 0, 5, 0, 0, 0, 5, 5, 5, 5, 5],
    'Mark': [3, 0, 0, 0, 0, 0, 0, 4, 0, 4, 4, 0, 0, 0, 0, 3, 0, 3],
    'Kat': [3, 3, 3, 4, 0, 0, 4, 4, 2, 4, 0, 5, 4, 0, 3, 3, 0, 4],
    'sgifedhw': [3, 5, 0, 3, 4, 0, 0, 3, 3, 4, 0, 0, 0, 3, 5, 5, 0, 0],
    'frogec': [5, 4, 0, 4, 0, 0, 0, 5, 1, 3, 4, 5, 0, 0, 4, 3, 0, 3],
    'IceTea': [4, 5, 0, 3, 0, 0, 0, 5, 0, 5, 0, 0, 3, 2, 0, 3, 0, 4],
    'Jz42': [3, 4, 3, 3, 0, 0, 5, 3, 0, 4, 0, 0, 0, 2, 2, 4, 0, 3],
    'GP': [4, 4, 2, 4, 4, 0, 5, 3, 3, 2, 0, 5, 4, 1, 4, 2, 5, 3],
    'robertcv': [3, 4, 4, 5, 5, 0, 5, 5, 0, 3, 0, 0, 0, 0, 5, 3, 0, 2],
    'frenkie': [4, 4, 3, 4, 4, 0, 5, 4, 2, 4, 0, 0, 0, 0, 4, 4, 0, 3],
    'JT': [4, 5, 3, 5, 4, 0, 0, 4, 0, 5, 0, 5, 5, 0, 4, 0, 0, 4],
    'Alen': [3, 5, 0, 4, 0, 0, 3, 4, 0, 4, 0, 0, 3, 2, 3, 4, 0, 0],
    'nejcr': [2, 3, 2, 3, 2, 2, 4, 2, 1, 2, 2, 4, 2, 2, 4, 2, 3, 3],
    'Bassgeta': [3, 5, 0, 4, 0, 5, 5, 4, 0, 5, 0, 5, 4, 0, 2, 2, 5, 0],
    'Matt': [4, 4, 5, 3, 0, 0, 0, 4, 0, 5, 0, 0, 0, 0, 2, 0, 0, 5],
    'Stickman': [5, 5, 4, 3, 4, 0, 0, 4, 2, 3, 0, 4, 4, 3, 4, 2, 0, 3],
    'iks': [4, 5, 3, 3, 5, 0, 0, 3, 0, 2, 0, 0, 3, 0, 0, 2, 5, 2],
    'muaddib': [2, 4, 0, 3, 5, 2, 5, 3, 0, 0, 0, 0, 5, 3, 5, 3, 0, 3],
    'Skankhunt42': [0, 0, 4, 5, 4, 2, 3, 0, 5, 3, 0, 0, 4, 0, 0, 3, 1, 4],
    'vid': [4, 4, 4, 3, 0, 0, 0, 4, 0, 5, 0, 5, 0, 0, 0, 4, 0, 3],
    'CaveExplorer': [4, 5, 0, 5, 5, 0, 0, 4, 0, 4, 0, 5, 0, 0, 0, 4, 5, 4],
    'Enej': [4, 5, 0, 4, 5, 0, 5, 3, 0, 0, 5, 4, 0, 3, 0, 3, 5, 4],
    'Greg': [3, 0, 4, 0, 5, 0, 0, 0, 0, 4, 0, 0, 0, 0, 4, 3, 0, 4]
}

INTERSECTIONS = {
    ("zm12345", "ATom"): [0, 1, 2, 3, 4, 5, 6, 7, 10, 12, 16],
    ("robertcv", "Mark"): [0, 7, 9, 15, 17],
    ("bq", "Voter003"): [1, 2, 6, 7, 9, 11, 13, 15, 17],
    ("sgifedhw", "ATom"): [0, 1, 3, 4, 7, 15],
    ("Student n", "Duco"): [1, 3, 4, 10, 12, 15],
    ("zm12345", "abcd"): [0, 1, 3, 7],
    ("blazb", "Kat"): [0, 1, 2, 3, 6, 7, 8, 9, 15, 17],
    ("sgifedhw", "Klemen K"): [0, 1, 3, 4, 7, 8, 9, 13, 14, 15],
    ("Rak", "Mark"): [0, 9, 15],
    ("X", "Bassgeta"): [0, 1, 3, 5, 6, 7, 9, 12, 15, 16],
}

VOTES = {
    'Titanic': {'deki': 4,
                'Rak': 3,
                'ATom': 4,
                'ivek': 3,
                'miso': 3,
                'ziga': 3,
                'nepoznalec': 4,
                'mx': 3,
                'blazb': 5,
                'jure': 4,
                'saso': 3,
                'Vida': 3,
                'sasha': 3,
                'majcn': 5,
                'zidar': 1,
                'mrbean': 3,
                'zm12345': 4,
                'Duco': 3,
                'Slovenc': 3,
                'HIP_HOP': 5,
                'X': 2,
                'Karlos': 5,
                'smotko': 3,
                'abcd': 3,
                'anika': 4,
                'Vatreni': 4,
                'ddrrt': 4,
                'ThePav': 3,
                'klobasa': 3,
                'kiwi': 4,
                'seven': 5,
                'gupi': 3,
                'Ish': 5,
                'Benjamin': 4,
                'marko': 4,
                'Batman': 3,
                'Andrej': 3,
                'patriotka': 3,
                'swizec': 5,
                "LorD_D'DooM": 2,
                'dwww': 3,
                'shroomz': 3,
                'MC': 3,
                'voter007': 3,
                'sedmica': 3,
                'uawe': 3,
                'lotus': 2,
                'agent007': 4,
                'Klemen K': 5,
                'bq': 2,
                'ad': 4,
                'Haris': 3,
                'Rdelca Kapica': 4,
                'Mark': 3,
                'Kat': 3,
                'sgifedhw': 3,
                'frogec': 5,
                'IceTea': 4,
                'Jz42': 3,
                'GP': 4,
                'robertcv': 3,
                'frenkie': 4,
                'JT': 4,
                'Alen': 3,
                'nejcr': 2,
                'Bassgeta': 3,
                'Matt': 4,
                'Stickman': 5,
                'iks': 4,
                'muaddib': 2,
                'vid': 4,
                'CaveExplorer': 4,
                'Enej': 4,
                'Greg': 3},
    'Matrix': {'deki': 5,
               'Janez': 3,
               'Rak': 5,
               'ATom': 5,
               'ivek': 5,
               'miso': 5,
               'ziga': 3,
               'mx': 5,
               'blazb': 3,
               'saso': 5,
               'Vida': 2,
               'majcn': 4,
               'zidar': 3,
               'mrbean': 3,
               'zm12345': 4,
               'HairyFotr': 5,
               'Duco': 5,
               'Slovenc': 4,
               'HIP_HOP': 5,
               'X': 5,
               'Karlos': 5,
               'smotko': 4,
               'abcd': 3,
               'Vatreni': 5,
               'Student n': 5,
               'ddrrt': 5,
               'ThePav': 5,
               'klobasa': 4,
               'kiwi': 5,
               'seven': 5,
               'Benjamin': 5,
               'marko': 5,
               'Batman': 5,
               'Andrej': 5,
               'patriotka': 3,
               'swizec': 4,
               "LorD_D'DooM": 3,
               'dwww': 4,
               'shroomz': 5,
               'MC': 4,
               'voter007': 4,
               'Voter003': 3,
               'sedmica': 3,
               'uawe': 5,
               'lotus': 5,
               'agent007': 5,
               'Klemen K': 5,
               'bq': 4,
               'motika': 5,
               'ad': 4,
               'Haris': 5,
               'Rdelca Kapica': 5,
               'Kat': 3,
               'sgifedhw': 5,
               'frogec': 4,
               'IceTea': 5,
               'Jz42': 4,
               'GP': 4,
               'robertcv': 4,
               'frenkie': 4,
               'JT': 5,
               'Alen': 5,
               'nejcr': 3,
               'Bassgeta': 5,
               'Matt': 4,
               'Stickman': 5,
               'iks': 5,
               'muaddib': 4,
               'vid': 4,
               'CaveExplorer': 5,
               'Enej': 5},
    'WALL-E': {'Janez': 4,
               'ATom': 5,
               'ivek': 5,
               'miso': 4,
               'nepoznalec': 4,
               'blazb': 5,
               'Vida': 5,
               'zidar': 5,
               'mrbean': 2,
               'zm12345': 2,
               'HairyFotr': 5,
               'Slovenc': 3,
               'HIP_HOP': 4,
               'X': 3,
               'Karlos': 4,
               'smotko': 5,
               'Vatreni': 5,
               'ddrrt': 4,
               'ThePav': 5,
               'klobasa': 5,
               'seven': 5,
               'marko': 3,
               'Batman': 4,
               'Andrej': 5,
               'patriotka': 2,
               'swizec': 5,
               "LorD_D'DooM": 5,
               'dwww': 3,
               'shroomz': 5,
               'MC': 4,
               'Voter003': 3,
               'sedmica': 5,
               'lotus': 4,
               'agent007': 3,
               'Klemen K': 2,
               'bq': 2,
               'motika': 3,
               'Haris': 4,
               'Rdelca Kapica': 5,
               'Kat': 3,
               'Jz42': 3,
               'GP': 2,
               'robertcv': 4,
               'frenkie': 3,
               'JT': 3,
               'nejcr': 2,
               'Matt': 5,
               'Stickman': 4,
               'iks': 3,
               'Skankhunt42': 4,
               'vid': 4,
               'Greg': 4},
    'Men in Black': {'deki': 4,
                     'Janez': 4,
                     'Rak': 4,
                     'ATom': 5,
                     'ivek': 4,
                     'ziga': 2,
                     'nepoznalec': 4,
                     'mx': 4,
                     'blazb': 3,
                     'jure': 2,
                     'saso': 5,
                     'Vida': 4,
                     'majcn': 2,
                     'zidar': 3,
                     'mrbean': 3,
                     'zm12345': 2,
                     'HairyFotr': 4,
                     'Duco': 3,
                     'Slovenc': 4,
                     'HIP_HOP': 4,
                     'X': 4,
                     'Karlos': 4,
                     'smotko': 4,
                     'abcd': 4,
                     'anika': 3,
                     'Vatreni': 3,
                     'Student n': 3,
                     'ddrrt': 3,
                     'ThePav': 4,
                     'klobasa': 3,
                     'kiwi': 4,
                     'seven': 4,
                     'gupi': 2,
                     'Benjamin': 4,
                     'marko': 3,
                     'patriotka': 2,
                     'swizec': 4,
                     "LorD_D'DooM": 1,
                     'dwww': 4,
                     'shroomz': 5,
                     'MC': 2,
                     'voter007': 5,
                     'Voter003': 4,
                     'sedmica': 4,
                     'uawe': 2,
                     'lotus': 5,
                     'agent007': 4,
                     'Klemen K': 3,
                     'motika': 5,
                     'ad': 4,
                     'Haris': 4,
                     'Rdelca Kapica': 5,
                     'Kat': 4,
                     'sgifedhw': 3,
                     'frogec': 4,
                     'IceTea': 3,
                     'Jz42': 3,
                     'GP': 4,
                     'robertcv': 5,
                     'frenkie': 4,
                     'JT': 5,
                     'Alen': 4,
                     'nejcr': 3,
                     'Bassgeta': 4,
                     'Matt': 3,
                     'Stickman': 3,
                     'iks': 3,
                     'muaddib': 3,
                     'Skankhunt42': 5,
                     'vid': 3,
                     'CaveExplorer': 5,
                     'Enej': 4},
    'A Beautiful Mind': {'Janez': 3,
                         'ATom': 5,
                         'ivek': 2,
                         'miso': 4,
                         'ziga': 4,
                         'mx': 4,
                         'zidar': 5,
                         'mrbean': 5,
                         'zm12345': 5,
                         'HairyFotr': 5,
                         'Duco': 4,
                         'Slovenc': 4,
                         'HIP_HOP': 5,
                         'X': 5,
                         'Karlos': 5,
                         'smotko': 5,
                         'anika': 4,
                         'Vatreni': 5,
                         'Student n': 4,
                         'ddrrt': 3,
                         'seven': 4,
                         'gupi': 5,
                         'Ish': 2,
                         'Benjamin': 5,
                         'marko': 5,
                         'Andrej': 5,
                         'patriotka': 4,
                         'swizec': 5,
                         'dwww': 4,
                         'MC': 5,
                         'sedmica': 4,
                         'uawe': 4,
                         'lotus': 4,
                         'agent007': 4,
                         'Klemen K': 3,
                         'bq': 3,
                         'ad': 3,
                         'Haris': 4,
                         'sgifedhw': 4,
                         'GP': 4,
                         'robertcv': 5,
                         'frenkie': 4,
                         'JT': 4,
                         'nejcr': 2,
                         'Stickman': 4,
                         'iks': 5,
                         'muaddib': 5,
                         'Skankhunt42': 4,
                         'CaveExplorer': 5,
                         'Enej': 5,
                         'Greg': 5},
    'Star Trek Nemesis': {'Rak': 2,
                          'ATom': 3,
                          'ivek': 4,
                          'mx': 4,
                          'sasha': 3,
                          'zidar': 4,
                          'mrbean': 4,
                          'zm12345': 2,
                          'Slovenc': 3,
                          'HIP_HOP': 4,
                          'X': 5,
                          'seven': 3,
                          'marko': 4,
                          "LorD_D'DooM": 4,
                          'dwww': 2,
                          'lotus': 3,
                          'nejcr': 2,
                          'Bassgeta': 5,
                          'muaddib': 2,
                          'Skankhunt42': 2},
    'The godfather': {'deki': 4,
                      'Janez': 5,
                      'ATom': 5,
                      'ivek': 3,
                      'ziga': 5,
                      'mx': 5,
                      'blazb': 4,
                      'Vida': 2,
                      'mrbean': 4,
                      'zm12345': 5,
                      'Duco': 5,
                      'HIP_HOP': 5,
                      'X': 5,
                      'smotko': 4,
                      'anika': 2,
                      'Vatreni': 5,
                      'ddrrt': 2,
                      'ThePav': 5,
                      'klobasa': 5,
                      'kiwi': 5,
                      'seven': 5,
                      'gupi': 5,
                      'Benjamin': 5,
                      'marko': 4,
                      'Andrej': 5,
                      'patriotka': 5,
                      'swizec': 3,
                      "LorD_D'DooM": 5,
                      'dwww': 3,
                      'shroomz': 5,
                      'MC': 5,
                      'Voter003': 3,
                      'uawe': 5,
                      'lotus': 4,
                      'Klemen K': 5,
                      'bq': 5,
                      'ad': 3,
                      'Rdelca Kapica': 4,
                      'Kat': 4,
                      'Jz42': 5,
                      'GP': 5,
                      'robertcv': 5,
                      'frenkie': 5,
                      'Alen': 3,
                      'nejcr': 4,
                      'Bassgeta': 5,
                      'muaddib': 5,
                      'Skankhunt42': 3,
                      'Enej': 5},
    'Pirates of the Carribean: Black Pearl': {'deki': 3,
                                              'Janez': 5,
                                              'ATom': 5,
                                              'ivek': 4,
                                              'miso': 5,
                                              'ziga': 2,
                                              'nepoznalec': 3,
                                              'mx': 2,
                                              'blazb': 3,
                                              'jure': 4,
                                              'saso': 4,
                                              'majcn': 5,
                                              'zidar': 2,
                                              'mrbean': 3,
                                              'zm12345': 3,
                                              'HairyFotr': 2,
                                              'Duco': 2,
                                              'Slovenc': 4,
                                              'HIP_HOP': 5,
                                              'X': 2,
                                              'Karlos': 5,
                                              'smotko': 3,
                                              'abcd': 4,
                                              'anika': 5,
                                              'Vatreni': 4,
                                              'ddrrt': 4,
                                              'ThePav': 5,
                                              'klobasa': 5,
                                              'kiwi': 3,
                                              'seven': 4,
                                              'gupi': 3,
                                              'Ish': 5,
                                              'Benjamin': 3,
                                              'marko': 4,
                                              'Batman': 5,
                                              'Andrej': 5,
                                              'patriotka': 4,
                                              'swizec': 5,
                                              "LorD_D'DooM": 3,
                                              'dwww': 2,
                                              'shroomz': 4,
                                              'MC': 5,
                                              'voter007': 5,
                                              'Voter003': 5,
                                              'sedmica': 4,
                                              'lotus': 4,
                                              'agent007': 5,
                                              'Klemen K': 2,
                                              'bq': 3,
                                              'motika': 3,
                                              'ad': 5,
                                              'Haris': 5,
                                              'Rdelca Kapica': 5,
                                              'Mark': 4,
                                              'Kat': 4,
                                              'sgifedhw': 3,
                                              'frogec': 5,
                                              'IceTea': 5,
                                              'Jz42': 3,
                                              'GP': 3,
                                              'robertcv': 5,
                                              'frenkie': 4,
                                              'JT': 4,
                                              'Alen': 4,
                                              'nejcr': 2,
                                              'Bassgeta': 4,
                                              'Matt': 4,
                                              'Stickman': 4,
                                              'iks': 3,
                                              'muaddib': 3,
                                              'vid': 4,
                                              'CaveExplorer': 4,
                                              'Enej': 3},
    'Sex and the City': {'deki': 1,
                         'Janez': 2,
                         'Rak': 2,
                         'ivek': 1,
                         'miso': 2,
                         'nepoznalec': 1,
                         'mx': 1,
                         'blazb': 1,
                         'Vida': 3,
                         'sasha': 2,
                         'Slovenc': 1,
                         'X': 2,
                         'smotko': 1,
                         'abcd': 4,
                         'anika': 1,
                         'seven': 2,
                         'gupi': 3,
                         'Ish': 3,
                         'marko': 1,
                         'dwww': 1,
                         'shroomz': 2,
                         'sedmica': 2,
                         'uawe': 1,
                         'lotus': 1,
                         'Klemen K': 1,
                         'ad': 2,
                         'Haris': 2,
                         'Kat': 2,
                         'sgifedhw': 3,
                         'frogec': 1,
                         'GP': 3,
                         'frenkie': 2,
                         'nejcr': 1,
                         'Stickman': 2,
                         'Skankhunt42': 5},
    'Harry Potter and the Deathly Hallows 2': {'deki': 1,
                                               'Janez': 4,
                                               'Rak': 4,
                                               'ivek': 1,
                                               'miso': 5,
                                               'nepoznalec': 3,
                                               'mx': 1,
                                               'blazb': 4,
                                               'jure': 4,
                                               'saso': 5,
                                               'majcn': 5,
                                               'zidar': 1,
                                               'mrbean': 1,
                                               'zm12345': 2,
                                               'HairyFotr': 3,
                                               'Duco': 2,
                                               'Slovenc': 3,
                                               'X': 3,
                                               'ThePav': 4,
                                               'kiwi': 4,
                                               'seven': 3,
                                               'Ish': 5,
                                               'Benjamin': 5,
                                               'marko': 3,
                                               'Andrej': 5,
                                               'patriotka': 3,
                                               "LorD_D'DooM": 1,
                                               'dwww': 1,
                                               'shroomz': 4,
                                               'MC': 2,
                                               'voter007': 3,
                                               'Voter003': 2,
                                               'sedmica': 4,
                                               'uawe': 3,
                                               'lotus': 3,
                                               'agent007': 3,
                                               'Klemen K': 1,
                                               'bq': 3,
                                               'motika': 2,
                                               'Haris': 5,
                                               'Rdelca Kapica': 5,
                                               'Mark': 4,
                                               'Kat': 4,
                                               'sgifedhw': 4,
                                               'frogec': 3,
                                               'IceTea': 5,
                                               'Jz42': 4,
                                               'GP': 2,
                                               'robertcv': 3,
                                               'frenkie': 4,
                                               'JT': 5,
                                               'Alen': 4,
                                               'nejcr': 2,
                                               'Bassgeta': 5,
                                               'Matt': 5,
                                               'Stickman': 3,
                                               'iks': 2,
                                               'Skankhunt42': 3,
                                               'vid': 5,
                                               'CaveExplorer': 4,
                                               'Greg': 4},
    'Life of Brian': {'Janez': 5,
                      'ATom': 5,
                      'mx': 5,
                      'blazb': 3,
                      'sasha': 5,
                      'zm12345': 3,
                      'HairyFotr': 5,
                      'Duco': 4,
                      'anika': 4,
                      'Vatreni': 5,
                      'Student n': 5,
                      'ddrrt': 4,
                      'ThePav': 4,
                      'seven': 5,
                      'Ish': 3,
                      'Andrej': 4,
                      'swizec': 5,
                      'dwww': 3,
                      'shroomz': 5,
                      'voter007': 5,
                      'uawe': 4,
                      'ad': 4,
                      'Mark': 4,
                      'frogec': 4,
                      'nejcr': 2,
                      'Enej': 5},
    'Pulp Fiction': {'deki': 4,
                     'Janez': 3,
                     'ziga': 5,
                     'mx': 5,
                     'saso': 4,
                     'zidar': 5,
                     'mrbean': 4,
                     'zm12345': 4,
                     'HairyFotr': 4,
                     'Duco': 5,
                     'HIP_HOP': 5,
                     'smotko': 5,
                     'anika': 2,
                     'ddrrt': 5,
                     'klobasa': 5,
                     'kiwi': 5,
                     'seven': 5,
                     'Benjamin': 5,
                     'marko': 5,
                     'patriotka': 5,
                     'swizec': 2,
                     "LorD_D'DooM": 5,
                     'dwww': 4,
                     'shroomz': 5,
                     'MC': 5,
                     'Voter003': 3,
                     'uawe': 5,
                     'lotus': 5,
                     'Klemen K': 5,
                     'bq': 5,
                     'motika': 2,
                     'ad': 4,
                     'Haris': 3,
                     'Kat': 5,
                     'frogec': 5,
                     'GP': 5,
                     'JT': 5,
                     'nejcr': 4,
                     'Bassgeta': 5,
                     'Stickman': 4,
                     'vid': 5,
                     'CaveExplorer': 5,
                     'Enej': 4},
    'Alien': {'ATom': 4,
              'ivek': 4,
              'miso': 3,
              'mx': 2,
              'jure': 3,
              'saso': 4,
              'sasha': 4,
              'zidar': 5,
              'zm12345': 2,
              'HairyFotr': 5,
              'Duco': 5,
              'HIP_HOP': 4,
              'X': 4,
              'Karlos': 2,
              'smotko': 4,
              'anika': 3,
              'Vatreni': 4,
              'Student n': 3,
              'ddrrt': 5,
              'ThePav': 4,
              'klobasa': 4,
              'seven': 5,
              'marko': 5,
              'Andrej': 5,
              'swizec': 5,
              "LorD_D'DooM": 5,
              'dwww': 4,
              'MC': 4,
              'sedmica': 3,
              'uawe': 3,
              'lotus': 1,
              'Klemen K': 5,
              'bq': 4,
              'motika': 5,
              'Haris': 3,
              'Kat': 4,
              'IceTea': 3,
              'GP': 4,
              'JT': 5,
              'Alen': 3,
              'nejcr': 2,
              'Bassgeta': 4,
              'Stickman': 4,
              'iks': 3,
              'muaddib': 5,
              'Skankhunt42': 4},
    'Petelinji zajtrk': {'Janez': 3,
                         'ivek': 3,
                         'ziga': 2,
                         'nepoznalec': 4,
                         'jure': 2,
                         'Vida': 1,
                         'majcn': 1,
                         'mrbean': 2,
                         'zm12345': 4,
                         'Slovenc': 4,
                         'HIP_HOP': 5,
                         'Karlos': 4,
                         'smotko': 3,
                         'anika': 4,
                         'Vatreni': 3,
                         'Student n': 2,
                         'seven': 4,
                         'gupi': 4,
                         'Ish': 1,
                         'Benjamin': 4,
                         'patriotka': 3,
                         'dwww': 1,
                         'shroomz': 1,
                         'voter007': 1,
                         'Voter003': 4,
                         'sedmica': 4,
                         'uawe': 3,
                         'lotus': 5,
                         'agent007': 4,
                         'Klemen K': 2,
                         'bq': 3,
                         'ad': 3,
                         'Rdelca Kapica': 5,
                         'sgifedhw': 3,
                         'IceTea': 2,
                         'Jz42': 2,
                         'GP': 1,
                         'Alen': 2,
                         'nejcr': 2,
                         'Stickman': 3,
                         'muaddib': 3,
                         'Enej': 3},
    'Rocky': {'deki': 3,
              'Janez': 2,
              'Rak': 3,
              'ivek': 3,
              'miso': 5,
              'ziga': 2,
              'nepoznalec': 3,
              'mx': 3,
              'jure': 3,
              'saso': 4,
              'Vida': 2,
              'sasha': 4,
              'zidar': 2,
              'mrbean': 1,
              'HairyFotr': 3,
              'Duco': 3,
              'Slovenc': 3,
              'HIP_HOP': 3,
              'Karlos': 5,
              'anika': 5,
              'Vatreni': 3,
              'ddrrt': 3,
              'seven': 4,
              'gupi': 3,
              'Benjamin': 5,
              'marko': 4,
              'patriotka': 2,
              'swizec': 4,
              'dwww': 3,
              'shroomz': 2,
              'MC': 4,
              'voter007': 5,
              'sedmica': 1,
              'uawe': 4,
              'lotus': 3,
              'agent007': 5,
              'Klemen K': 2,
              'ad': 3,
              'Haris': 4,
              'Rdelca Kapica': 5,
              'Kat': 3,
              'sgifedhw': 5,
              'frogec': 4,
              'Jz42': 2,
              'GP': 4,
              'robertcv': 5,
              'frenkie': 4,
              'JT': 4,
              'Alen': 3,
              'nejcr': 4,
              'Bassgeta': 2,
              'Matt': 2,
              'Stickman': 4,
              'muaddib': 5,
              'Greg': 4},
    'American Pie': {'deki': 3,
                     'Janez': 2,
                     'Rak': 5,
                     'ATom': 1,
                     'ivek': 5,
                     'miso': 4,
                     'ziga': 2,
                     'nepoznalec': 3,
                     'mx': 1,
                     'blazb': 3,
                     'jure': 2,
                     'saso': 3,
                     'Vida': 1,
                     'majcn': 3,
                     'zidar': 1,
                     'mrbean': 3,
                     'Duco': 2,
                     'Slovenc': 2,
                     'HIP_HOP': 3,
                     'X': 4,
                     'Karlos': 3,
                     'smotko': 1,
                     'abcd': 2,
                     'anika': 3,
                     'Vatreni': 3,
                     'Student n': 2,
                     'klobasa': 3,
                     'kiwi': 2,
                     'seven': 5,
                     'gupi': 3,
                     'Benjamin': 3,
                     'marko': 2,
                     'Batman': 3,
                     'patriotka': 4,
                     'swizec': 3,
                     "LorD_D'DooM": 1,
                     'dwww': 2,
                     'shroomz': 3,
                     'MC': 1,
                     'voter007': 4,
                     'Voter003': 4,
                     'sedmica': 5,
                     'uawe': 2,
                     'lotus': 4,
                     'agent007': 4,
                     'Klemen K': 4,
                     'bq': 1,
                     'motika': 4,
                     'ad': 4,
                     'Haris': 3,
                     'Rdelca Kapica': 5,
                     'Mark': 3,
                     'Kat': 3,
                     'sgifedhw': 5,
                     'frogec': 3,
                     'IceTea': 3,
                     'Jz42': 4,
                     'GP': 2,
                     'robertcv': 3,
                     'frenkie': 4,
                     'Alen': 4,
                     'nejcr': 2,
                     'Bassgeta': 2,
                     'Stickman': 2,
                     'iks': 2,
                     'muaddib': 3,
                     'Skankhunt42': 3,
                     'vid': 4,
                     'CaveExplorer': 4,
                     'Enej': 3,
                     'Greg': 3},
    "Schindler's List": {'deki': 5,
                         'ATom': 5,
                         'ivek': 2,
                         'mx': 5,
                         'blazb': 4,
                         'jure': 4,
                         'saso': 5,
                         'Vida': 4,
                         'zidar': 1,
                         'zm12345': 5,
                         'Duco': 4,
                         'Slovenc': 3,
                         'HIP_HOP': 4,
                         'X': 5,
                         'smotko': 5,
                         'anika': 4,
                         'Vatreni': 5,
                         'ddrrt': 4,
                         'ThePav': 5,
                         'klobasa': 5,
                         'kiwi': 5,
                         'seven': 4,
                         'gupi': 5,
                         'Benjamin': 5,
                         'marko': 5,
                         'patriotka': 5,
                         'swizec': 4,
                         "LorD_D'DooM": 5,
                         'dwww': 5,
                         'shroomz': 5,
                         'uawe': 4,
                         'lotus': 5,
                         'agent007': 3,
                         'Klemen K': 5,
                         'bq': 5,
                         'Haris': 4,
                         'Rdelca Kapica': 5,
                         'GP': 5,
                         'nejcr': 3,
                         'Bassgeta': 5,
                         'iks': 5,
                         'Skankhunt42': 1,
                         'CaveExplorer': 5,
                         'Enej': 5},
    'Ice Age: Dawn of the Dinosaurs': {'deki': 3,
                                       'Janez': 5,
                                       'ATom': 4,
                                       'ivek': 4,
                                       'miso': 4,
                                       'ziga': 2,
                                       'nepoznalec': 3,
                                       'mx': 1,
                                       'blazb': 4,
                                       'jure': 4,
                                       'Vida': 5,
                                       'sasha': 3,
                                       'majcn': 5,
                                       'zidar': 5,
                                       'mrbean': 4,
                                       'Slovenc': 3,
                                       'HIP_HOP': 5,
                                       'X': 3,
                                       'Karlos': 2,
                                       'smotko': 1,
                                       'abcd': 4,
                                       'anika': 5,
                                       'Vatreni': 3,
                                       'ddrrt': 3,
                                       'ThePav': 3,
                                       'klobasa': 4,
                                       'kiwi': 4,
                                       'seven': 3,
                                       'gupi': 4,
                                       'Ish': 3,
                                       'Benjamin': 4,
                                       'marko': 3,
                                       'Batman': 3,
                                       'Andrej': 4,
                                       'patriotka': 4,
                                       "LorD_D'DooM": 4,
                                       'dwww': 4,
                                       'shroomz': 4,
                                       'MC': 2,
                                       'voter007': 5,
                                       'Voter003': 5,
                                       'sedmica': 3,
                                       'lotus': 4,
                                       'agent007': 5,
                                       'Klemen K': 2,
                                       'bq': 2,
                                       'motika': 3,
                                       'ad': 4,
                                       'Haris': 3,
                                       'Rdelca Kapica': 5,
                                       'Mark': 3,
                                       'Kat': 4,
                                       'frogec': 3,
                                       'IceTea': 4,
                                       'Jz42': 3,
                                       'GP': 3,
                                       'robertcv': 2,
                                       'frenkie': 3,
                                       'JT': 4,
                                       'nejcr': 3,
                                       'Matt': 5,
                                       'Stickman': 3,
                                       'iks': 2,
                                       'muaddib': 3,
                                       'Skankhunt42': 4,
                                       'vid': 3,
                                       'CaveExplorer': 4,
                                       'Enej': 4,
                                       'Greg': 4}}

EXTRA_DATA_FILE = "extra.csv"

EXTRA_READ = [
    ['under preserve perhaps', 'thriller', 1965, 69.55],
    ['broken special flavor craft', 'historical', 1941, 234.27],
    ['feed physician mistake', 'crime', 1965, 181.0],
    ['arise regional away permit', 'fantasy', 1994, 199.83],
    ['forth score', 'magical realism', 1966, 105.7],
    ['particular display sense', 'magical realism', 2016, 203.48],
    ['surprise', 'social', 2009, 231.35],
    ['make craft specific connection', 'paranoid fiction', 1954, 239.05],
    ['memory membership french fish', 'mystery', 1963, 167.9],
    ['milk form interview', 'magical realism', 1939, 126.15],
    ['yard load', 'satire', 1972, 158.0],
    ['basically shirt surgery', 'magical realism', 2012, 192.2],
    ['state', 'philosophical', 1983, 94.02],
    ['crowd predict new acknowledge', 'thriller', 1954, 142.07],
    ['assumption account list palm', 'philosophical', 1950, 69.97],
    ['heaven', 'science fiction', 1943, 83.4],
    ['know throat regardless', 'science fiction', 1983, 120.75],
    ['tail tongue', 'science fiction', 1941, 60.88],
    ['unit prisoner obvious', 'drama', 1962, 209.95],
    ['sophisticated invite flee', 'historical fiction', 1971, 104.57],
    ['venture hunter largely', 'science fiction', 1996, 122.37],
    ['assumption', 'social', 1970, 73.87],
    ['soil', 'crime', 2001, 87.57],
    ['hundred bank', 'social', 2016, 89.67],
    ['neighbor resort', 'speculative', 2006, 157.62],
    ['million teen feature', 'crime', 1995, 158.08],
    ['versus representation', 'science fiction', 1969, 128.1],
    ['believe welfare', 'speculative', 1983, 97.57],
    ['eastern least knock wealth', 'speculative', 1964, 207.3],
    ['he reply suggest', 'paranoid fiction', 1987, 142.85]]

EXTRA_GENRE = {
    'speculative': 154.16,
    'science fiction': 103.1,
    'magical realism': 156.88,
    'thriller': 105.81,
    'mystery': 167.9,
    'fantasy': 199.83,
    'historical fiction': 104.57,
    'crime': 142.22,
    'satire': 158.0,
    'historical': 234.27,
    'philosophical': 82.0,
    'paranoid fiction': 190.95,
    'social': 131.63,
    'drama': 209.95}

EXTRA_RATINGS = {
    'EmilyThomas54': [2, 1, 4, 0, 2, 4, 5, 0, 2, 5, 5, 1, 1, 1, 3, 1, 4, 4, 2, 5, 2, 1, 5, 3, 4, 0, 0, 5, 3, 1],
    'SusanJones40': [0, 5, 3, 0, 2, 2, 4, 1, 5, 5, 5, 0, 1, 5, 3, 1, 3, 3, 2, 0, 0, 5, 0, 4, 1, 2, 5, 5, 2, 1],
    'KennethCastillo64': [1, 4, 3, 1, 1, 2, 3, 4, 1, 5, 4, 2, 1, 1, 1, 5, 5, 0, 1, 5, 5, 5, 2, 0, 0, 1, 2, 2, 0, 0],
    'MichelleLee80': [2, 5, 3, 1, 4, 5, 5, 2, 5, 3, 1, 3, 0, 3, 2, 1, 4, 5, 2, 0, 0, 5, 1, 2, 1, 5, 5, 3, 5, 5],
    'BrianWilliams32': [0, 1, 5, 2, 5, 2, 1, 0, 4, 0, 1, 5, 0, 3, 1, 1, 3, 0, 4, 5, 5, 4, 4, 0, 5, 4, 2, 0, 5, 4],
    'KarenPerez34': [0, 4, 2, 2, 5, 1, 3, 3, 0, 1, 4, 1, 2, 4, 2, 5, 5, 4, 3, 3, 1, 3, 0, 4, 5, 2, 4, 1, 3, 5],
    'EdwardHarris8': [4, 1, 2, 4, 2, 3, 2, 1, 0, 1, 4, 2, 4, 2, 3, 2, 5, 1, 0, 5, 1, 0, 4, 4, 3, 5, 1, 0, 0, 1],
    'DonnaSmith26': [3, 3, 5, 4, 2, 1, 4, 0, 0, 2, 0, 2, 4, 2, 2, 3, 3, 0, 0, 4, 1, 5, 2, 4, 5, 4, 3, 4, 5, 0],
    'LisaGomez49': [4, 2, 2, 5, 0, 1, 0, 2, 1, 5, 2, 4, 0, 5, 4, 3, 5, 0, 2, 5, 0, 1, 2, 5, 5, 4, 4, 3, 1, 2],
    'KevinMartin53': [3, 4, 0, 3, 3, 2, 2, 3, 4, 0, 5, 4, 4, 0, 5, 1, 3, 3, 4, 0, 1, 2, 4, 1, 1, 5, 5, 2, 1, 5],
    'AshleyTrevino10': [1, 5, 1, 0, 4, 3, 3, 3, 1, 1, 4, 0, 4, 5, 2, 2, 0, 3, 4, 2, 0, 5, 0, 2, 0, 3, 5, 4, 4, 2],
    'JessicaGarcia99': [5, 2, 2, 1, 5, 0, 0, 2, 1, 3, 1, 4, 2, 0, 4, 1, 0, 4, 0, 5, 2, 2, 5, 3, 5, 0, 3, 5, 0, 5],
    'StevenAnderson64': [2, 5, 0, 2, 5, 4, 3, 5, 3, 5, 5, 0, 1, 0, 2, 3, 5, 0, 2, 3, 1, 4, 5, 3, 2, 4, 3, 2, 3, 4],
    'MatthewGonzales10': [4, 1, 0, 4, 5, 1, 5, 5, 0, 3, 4, 2, 1, 3, 0, 1, 0, 1, 4, 5, 2, 5, 3, 1, 5, 3, 4, 1, 5, 2],
    'StevenScott48': [0, 1, 2, 4, 1, 2, 3, 3, 2, 4, 3, 2, 1, 2, 5, 0, 1, 0, 0, 0, 0, 4, 1, 1, 0, 4, 1, 0, 2, 5],
    'AndrewThomas93': [2, 4, 1, 0, 3, 1, 5, 3, 4, 5, 3, 1, 2, 3, 0, 0, 3, 3, 0, 5, 3, 2, 4, 0, 5, 1, 4, 1, 5, 4],
    'EmilyMartinez19': [1, 4, 0, 2, 4, 0, 1, 1, 4, 4, 0, 0, 4, 5, 1, 0, 4, 4, 0, 3, 4, 2, 0, 2, 3, 0, 4, 4, 2, 1],
    'JosephSmith26': [1, 5, 2, 3, 5, 2, 2, 0, 2, 4, 0, 1, 4, 4, 5, 4, 3, 3, 1, 0, 2, 2, 2, 2, 2, 5, 4, 3, 4, 2],
    'ThomasMiller84': [5, 2, 4, 4, 5, 0, 1, 0, 4, 4, 3, 1, 0, 3, 0, 0, 0, 1, 3, 1, 2, 5, 1, 1, 3, 0, 0, 0, 3, 1],
    'JosephWalker15': [0, 1, 5, 1, 3, 4, 2, 4, 0, 2, 2, 0, 0, 5, 1, 4, 5, 1, 3, 2, 1, 2, 2, 3, 2, 5, 1, 5, 5, 5],
    'MaryTrevino47': [5, 2, 3, 0, 4, 1, 3, 5, 4, 0, 1, 1, 1, 4, 5, 3, 3, 0, 3, 4, 1, 0, 0, 0, 3, 4, 4, 1, 3, 1],
    'JosephGutierrez92': [0, 0, 2, 3, 1, 1, 2, 3, 0, 4, 2, 2, 5, 5, 3, 3, 1, 2, 1, 0, 5, 2, 0, 1, 0, 2, 3, 1, 0, 3],
    'RichardMiller81': [4, 1, 1, 1, 3, 1, 5, 0, 5, 2, 4, 0, 0, 2, 1, 0, 0, 2, 5, 2, 0, 4, 2, 5, 5, 1, 3, 0, 0, 4],
    'JessicaGreen37': [2, 1, 3, 5, 3, 4, 3, 5, 1, 3, 0, 1, 3, 3, 1, 1, 0, 1, 0, 1, 2, 3, 2, 1, 0, 5, 2, 0, 3, 2],
    'JoshuaHall81': [4, 3, 0, 3, 2, 2, 2, 5, 0, 4, 3, 2, 2, 5, 1, 4, 5, 3, 2, 4, 0, 3, 3, 5, 5, 5, 1, 4, 1, 5],
    'StevenVasquez67': [1, 5, 5, 3, 4, 4, 4, 2, 1, 3, 3, 3, 2, 3, 4, 5, 3, 5, 5, 5, 2, 5, 0, 1, 0, 4, 5, 5, 2, 4],
    'AshleyJones61': [5, 4, 3, 5, 1, 0, 4, 2, 3, 5, 4, 4, 2, 3, 0, 5, 2, 4, 2, 1, 5, 2, 1, 4, 2, 5, 0, 0, 3, 5],
    'MargaretGarza1': [0, 3, 0, 3, 2, 3, 3, 3, 0, 0, 5, 2, 2, 5, 2, 5, 0, 5, 4, 0, 4, 2, 2, 3, 0, 3, 5, 5, 2, 4],
    'DonnaJackson12': [4, 3, 4, 1, 3, 4, 1, 2, 3, 0, 4, 0, 1, 4, 4, 0, 2, 5, 5, 4, 0, 0, 2, 4, 1, 5, 2, 1, 5, 2],
    'KevinMoore98': [4, 0, 0, 4, 3, 0, 0, 3, 3, 1, 1, 1, 2, 2, 1, 0, 5, 5, 5, 0, 0, 0, 0, 4, 4, 3, 4, 3, 3, 1]}

EXTRA_VOTES = {
    'under preserve perhaps': {'EmilyThomas54': 2,
                               'KennethCastillo64': 1,
                               'MichelleLee80': 2,
                               'EdwardHarris8': 4,
                               'DonnaSmith26': 3,
                               'LisaGomez49': 4,
                               'KevinMartin53': 3,
                               'AshleyTrevino10': 1,
                               'JessicaGarcia99': 5,
                               'StevenAnderson64': 2,
                               'MatthewGonzales10': 4,
                               'AndrewThomas93': 2,
                               'EmilyMartinez19': 1,
                               'JosephSmith26': 1,
                               'ThomasMiller84': 5,
                               'MaryTrevino47': 5,
                               'RichardMiller81': 4,
                               'JessicaGreen37': 2,
                               'JoshuaHall81': 4,
                               'StevenVasquez67': 1,
                               'AshleyJones61': 5,
                               'DonnaJackson12': 4,
                               'KevinMoore98': 4},
    'broken special flavor craft': {'EmilyThomas54': 1,
                                    'SusanJones40': 5,
                                    'KennethCastillo64': 4,
                                    'MichelleLee80': 5,
                                    'BrianWilliams32': 1,
                                    'KarenPerez34': 4,
                                    'EdwardHarris8': 1,
                                    'DonnaSmith26': 3,
                                    'LisaGomez49': 2,
                                    'KevinMartin53': 4,
                                    'AshleyTrevino10': 5,
                                    'JessicaGarcia99': 2,
                                    'StevenAnderson64': 5,
                                    'MatthewGonzales10': 1,
                                    'StevenScott48': 1,
                                    'AndrewThomas93': 4,
                                    'EmilyMartinez19': 4,
                                    'JosephSmith26': 5,
                                    'ThomasMiller84': 2,
                                    'JosephWalker15': 1,
                                    'MaryTrevino47': 2,
                                    'RichardMiller81': 1,
                                    'JessicaGreen37': 1,
                                    'JoshuaHall81': 3,
                                    'StevenVasquez67': 5,
                                    'AshleyJones61': 4,
                                    'MargaretGarza1': 3,
                                    'DonnaJackson12': 3},
    'feed physician mistake': {'EmilyThomas54': 4,
                               'SusanJones40': 3,
                               'KennethCastillo64': 3,
                               'MichelleLee80': 3,
                               'BrianWilliams32': 5,
                               'KarenPerez34': 2,
                               'EdwardHarris8': 2,
                               'DonnaSmith26': 5,
                               'LisaGomez49': 2,
                               'AshleyTrevino10': 1,
                               'JessicaGarcia99': 2,
                               'StevenScott48': 2,
                               'AndrewThomas93': 1,
                               'JosephSmith26': 2,
                               'ThomasMiller84': 4,
                               'JosephWalker15': 5,
                               'MaryTrevino47': 3,
                               'JosephGutierrez92': 2,
                               'RichardMiller81': 1,
                               'JessicaGreen37': 3,
                               'StevenVasquez67': 5,
                               'AshleyJones61': 3,
                               'DonnaJackson12': 4},
    'arise regional away permit': {'KennethCastillo64': 1,
                                   'MichelleLee80': 1,
                                   'BrianWilliams32': 2,
                                   'KarenPerez34': 2,
                                   'EdwardHarris8': 4,
                                   'DonnaSmith26': 4,
                                   'LisaGomez49': 5,
                                   'KevinMartin53': 3,
                                   'JessicaGarcia99': 1,
                                   'StevenAnderson64': 2,
                                   'MatthewGonzales10': 4,
                                   'StevenScott48': 4,
                                   'EmilyMartinez19': 2,
                                   'JosephSmith26': 3,
                                   'ThomasMiller84': 4,
                                   'JosephWalker15': 1,
                                   'JosephGutierrez92': 3,
                                   'RichardMiller81': 1,
                                   'JessicaGreen37': 5,
                                   'JoshuaHall81': 3,
                                   'StevenVasquez67': 3,
                                   'AshleyJones61': 5,
                                   'MargaretGarza1': 3,
                                   'DonnaJackson12': 1,
                                   'KevinMoore98': 4},
    'forth score': {'EmilyThomas54': 2,
                    'SusanJones40': 2,
                    'KennethCastillo64': 1,
                    'MichelleLee80': 4,
                    'BrianWilliams32': 5,
                    'KarenPerez34': 5,
                    'EdwardHarris8': 2,
                    'DonnaSmith26': 2,
                    'KevinMartin53': 3,
                    'AshleyTrevino10': 4,
                    'JessicaGarcia99': 5,
                    'StevenAnderson64': 5,
                    'MatthewGonzales10': 5,
                    'StevenScott48': 1,
                    'AndrewThomas93': 3,
                    'EmilyMartinez19': 4,
                    'JosephSmith26': 5,
                    'ThomasMiller84': 5,
                    'JosephWalker15': 3,
                    'MaryTrevino47': 4,
                    'JosephGutierrez92': 1,
                    'RichardMiller81': 3,
                    'JessicaGreen37': 3,
                    'JoshuaHall81': 2,
                    'StevenVasquez67': 4,
                    'AshleyJones61': 1,
                    'MargaretGarza1': 2,
                    'DonnaJackson12': 3,
                    'KevinMoore98': 3},
    'particular display sense': {'EmilyThomas54': 4,
                                 'SusanJones40': 2,
                                 'KennethCastillo64': 2,
                                 'MichelleLee80': 5,
                                 'BrianWilliams32': 2,
                                 'KarenPerez34': 1,
                                 'EdwardHarris8': 3,
                                 'DonnaSmith26': 1,
                                 'LisaGomez49': 1,
                                 'KevinMartin53': 2,
                                 'AshleyTrevino10': 3,
                                 'StevenAnderson64': 4,
                                 'MatthewGonzales10': 1,
                                 'StevenScott48': 2,
                                 'AndrewThomas93': 1,
                                 'JosephSmith26': 2,
                                 'JosephWalker15': 4,
                                 'MaryTrevino47': 1,
                                 'JosephGutierrez92': 1,
                                 'RichardMiller81': 1,
                                 'JessicaGreen37': 4,
                                 'JoshuaHall81': 2,
                                 'StevenVasquez67': 4,
                                 'MargaretGarza1': 3,
                                 'DonnaJackson12': 4},
    'surprise': {'EmilyThomas54': 5,
                 'SusanJones40': 4,
                 'KennethCastillo64': 3,
                 'MichelleLee80': 5,
                 'BrianWilliams32': 1,
                 'KarenPerez34': 3,
                 'EdwardHarris8': 2,
                 'DonnaSmith26': 4,
                 'KevinMartin53': 2,
                 'AshleyTrevino10': 3,
                 'StevenAnderson64': 3,
                 'MatthewGonzales10': 5,
                 'StevenScott48': 3,
                 'AndrewThomas93': 5,
                 'EmilyMartinez19': 1,
                 'JosephSmith26': 2,
                 'ThomasMiller84': 1,
                 'JosephWalker15': 2,
                 'MaryTrevino47': 3,
                 'JosephGutierrez92': 2,
                 'RichardMiller81': 5,
                 'JessicaGreen37': 3,
                 'JoshuaHall81': 2,
                 'StevenVasquez67': 4,
                 'AshleyJones61': 4,
                 'MargaretGarza1': 3,
                 'DonnaJackson12': 1},
    'make craft specific connection': {'SusanJones40': 1,
                                       'KennethCastillo64': 4,
                                       'MichelleLee80': 2,
                                       'KarenPerez34': 3,
                                       'EdwardHarris8': 1,
                                       'LisaGomez49': 2,
                                       'KevinMartin53': 3,
                                       'AshleyTrevino10': 3,
                                       'JessicaGarcia99': 2,
                                       'StevenAnderson64': 5,
                                       'MatthewGonzales10': 5,
                                       'StevenScott48': 3,
                                       'AndrewThomas93': 3,
                                       'EmilyMartinez19': 1,
                                       'JosephWalker15': 4,
                                       'MaryTrevino47': 5,
                                       'JosephGutierrez92': 3,
                                       'JessicaGreen37': 5,
                                       'JoshuaHall81': 5,
                                       'StevenVasquez67': 2,
                                       'AshleyJones61': 2,
                                       'MargaretGarza1': 3,
                                       'DonnaJackson12': 2,
                                       'KevinMoore98': 3},
    'memory membership french fish': {'EmilyThomas54': 2,
                                      'SusanJones40': 5,
                                      'KennethCastillo64': 1,
                                      'MichelleLee80': 5,
                                      'BrianWilliams32': 4,
                                      'LisaGomez49': 1,
                                      'KevinMartin53': 4,
                                      'AshleyTrevino10': 1,
                                      'JessicaGarcia99': 1,
                                      'StevenAnderson64': 3,
                                      'StevenScott48': 2,
                                      'AndrewThomas93': 4,
                                      'EmilyMartinez19': 4,
                                      'JosephSmith26': 2,
                                      'ThomasMiller84': 4,
                                      'MaryTrevino47': 4,
                                      'RichardMiller81': 5,
                                      'JessicaGreen37': 1,
                                      'StevenVasquez67': 1,
                                      'AshleyJones61': 3,
                                      'DonnaJackson12': 3,
                                      'KevinMoore98': 3},
    'milk form interview': {'EmilyThomas54': 5,
                            'SusanJones40': 5,
                            'KennethCastillo64': 5,
                            'MichelleLee80': 3,
                            'KarenPerez34': 1,
                            'EdwardHarris8': 1,
                            'DonnaSmith26': 2,
                            'LisaGomez49': 5,
                            'AshleyTrevino10': 1,
                            'JessicaGarcia99': 3,
                            'StevenAnderson64': 5,
                            'MatthewGonzales10': 3,
                            'StevenScott48': 4,
                            'AndrewThomas93': 5,
                            'EmilyMartinez19': 4,
                            'JosephSmith26': 4,
                            'ThomasMiller84': 4,
                            'JosephWalker15': 2,
                            'JosephGutierrez92': 4,
                            'RichardMiller81': 2,
                            'JessicaGreen37': 3,
                            'JoshuaHall81': 4,
                            'StevenVasquez67': 3,
                            'AshleyJones61': 5,
                            'KevinMoore98': 1},
    'yard load': {'EmilyThomas54': 5,
                  'SusanJones40': 5,
                  'KennethCastillo64': 4,
                  'MichelleLee80': 1,
                  'BrianWilliams32': 1,
                  'KarenPerez34': 4,
                  'EdwardHarris8': 4,
                  'LisaGomez49': 2,
                  'KevinMartin53': 5,
                  'AshleyTrevino10': 4,
                  'JessicaGarcia99': 1,
                  'StevenAnderson64': 5,
                  'MatthewGonzales10': 4,
                  'StevenScott48': 3,
                  'AndrewThomas93': 3,
                  'ThomasMiller84': 3,
                  'JosephWalker15': 2,
                  'MaryTrevino47': 1,
                  'JosephGutierrez92': 2,
                  'RichardMiller81': 4,
                  'JoshuaHall81': 3,
                  'StevenVasquez67': 3,
                  'AshleyJones61': 4,
                  'MargaretGarza1': 5,
                  'DonnaJackson12': 4,
                  'KevinMoore98': 1},
    'basically shirt surgery': {'EmilyThomas54': 1,
                                'KennethCastillo64': 2,
                                'MichelleLee80': 3,
                                'BrianWilliams32': 5,
                                'KarenPerez34': 1,
                                'EdwardHarris8': 2,
                                'DonnaSmith26': 2,
                                'LisaGomez49': 4,
                                'KevinMartin53': 4,
                                'JessicaGarcia99': 4,
                                'MatthewGonzales10': 2,
                                'StevenScott48': 2,
                                'AndrewThomas93': 1,
                                'JosephSmith26': 1,
                                'ThomasMiller84': 1,
                                'MaryTrevino47': 1,
                                'JosephGutierrez92': 2,
                                'JessicaGreen37': 1,
                                'JoshuaHall81': 2,
                                'StevenVasquez67': 3,
                                'AshleyJones61': 4,
                                'MargaretGarza1': 2,
                                'KevinMoore98': 1},
    'state': {'EmilyThomas54': 1,
              'SusanJones40': 1,
              'KennethCastillo64': 1,
              'KarenPerez34': 2,
              'EdwardHarris8': 4,
              'DonnaSmith26': 4,
              'KevinMartin53': 4,
              'AshleyTrevino10': 4,
              'JessicaGarcia99': 2,
              'StevenAnderson64': 1,
              'MatthewGonzales10': 1,
              'StevenScott48': 1,
              'AndrewThomas93': 2,
              'EmilyMartinez19': 4,
              'JosephSmith26': 4,
              'MaryTrevino47': 1,
              'JosephGutierrez92': 5,
              'JessicaGreen37': 3,
              'JoshuaHall81': 2,
              'StevenVasquez67': 2,
              'AshleyJones61': 2,
              'MargaretGarza1': 2,
              'DonnaJackson12': 1,
              'KevinMoore98': 2},
    'crowd predict new acknowledge': {'EmilyThomas54': 1,
                                      'SusanJones40': 5,
                                      'KennethCastillo64': 1,
                                      'MichelleLee80': 3,
                                      'BrianWilliams32': 3,
                                      'KarenPerez34': 4,
                                      'EdwardHarris8': 2,
                                      'DonnaSmith26': 2,
                                      'LisaGomez49': 5,
                                      'AshleyTrevino10': 5,
                                      'MatthewGonzales10': 3,
                                      'StevenScott48': 2,
                                      'AndrewThomas93': 3,
                                      'EmilyMartinez19': 5,
                                      'JosephSmith26': 4,
                                      'ThomasMiller84': 3,
                                      'JosephWalker15': 5,
                                      'MaryTrevino47': 4,
                                      'JosephGutierrez92': 5,
                                      'RichardMiller81': 2,
                                      'JessicaGreen37': 3,
                                      'JoshuaHall81': 5,
                                      'StevenVasquez67': 3,
                                      'AshleyJones61': 3,
                                      'MargaretGarza1': 5,
                                      'DonnaJackson12': 4,
                                      'KevinMoore98': 2},
    'assumption account list palm': {'EmilyThomas54': 3,
                                     'SusanJones40': 3,
                                     'KennethCastillo64': 1,
                                     'MichelleLee80': 2,
                                     'BrianWilliams32': 1,
                                     'KarenPerez34': 2,
                                     'EdwardHarris8': 3,
                                     'DonnaSmith26': 2,
                                     'LisaGomez49': 4,
                                     'KevinMartin53': 5,
                                     'AshleyTrevino10': 2,
                                     'JessicaGarcia99': 4,
                                     'StevenAnderson64': 2,
                                     'StevenScott48': 5,
                                     'EmilyMartinez19': 1,
                                     'JosephSmith26': 5,
                                     'JosephWalker15': 1,
                                     'MaryTrevino47': 5,
                                     'JosephGutierrez92': 3,
                                     'RichardMiller81': 1,
                                     'JessicaGreen37': 1,
                                     'JoshuaHall81': 1,
                                     'StevenVasquez67': 4,
                                     'MargaretGarza1': 2,
                                     'DonnaJackson12': 4,
                                     'KevinMoore98': 1},
    'heaven': {'EmilyThomas54': 1,
               'SusanJones40': 1,
               'KennethCastillo64': 5,
               'MichelleLee80': 1,
               'BrianWilliams32': 1,
               'KarenPerez34': 5,
               'EdwardHarris8': 2,
               'DonnaSmith26': 3,
               'LisaGomez49': 3,
               'KevinMartin53': 1,
               'AshleyTrevino10': 2,
               'JessicaGarcia99': 1,
               'StevenAnderson64': 3,
               'MatthewGonzales10': 1,
               'JosephSmith26': 4,
               'JosephWalker15': 4,
               'MaryTrevino47': 3,
               'JosephGutierrez92': 3,
               'JessicaGreen37': 1,
               'JoshuaHall81': 4,
               'StevenVasquez67': 5,
               'AshleyJones61': 5,
               'MargaretGarza1': 5},
    'know throat regardless': {'EmilyThomas54': 4,
                               'SusanJones40': 3,
                               'KennethCastillo64': 5,
                               'MichelleLee80': 4,
                               'BrianWilliams32': 3,
                               'KarenPerez34': 5,
                               'EdwardHarris8': 5,
                               'DonnaSmith26': 3,
                               'LisaGomez49': 5,
                               'KevinMartin53': 3,
                               'StevenAnderson64': 5,
                               'StevenScott48': 1,
                               'AndrewThomas93': 3,
                               'EmilyMartinez19': 4,
                               'JosephSmith26': 3,
                               'JosephWalker15': 5,
                               'MaryTrevino47': 3,
                               'JosephGutierrez92': 1,
                               'JoshuaHall81': 5,
                               'StevenVasquez67': 3,
                               'AshleyJones61': 2,
                               'DonnaJackson12': 2,
                               'KevinMoore98': 5},
    'tail tongue': {'EmilyThomas54': 4,
                    'SusanJones40': 3,
                    'MichelleLee80': 5,
                    'KarenPerez34': 4,
                    'EdwardHarris8': 1,
                    'KevinMartin53': 3,
                    'AshleyTrevino10': 3,
                    'JessicaGarcia99': 4,
                    'MatthewGonzales10': 1,
                    'AndrewThomas93': 3,
                    'EmilyMartinez19': 4,
                    'JosephSmith26': 3,
                    'ThomasMiller84': 1,
                    'JosephWalker15': 1,
                    'JosephGutierrez92': 2,
                    'RichardMiller81': 2,
                    'JessicaGreen37': 1,
                    'JoshuaHall81': 3,
                    'StevenVasquez67': 5,
                    'AshleyJones61': 4,
                    'MargaretGarza1': 5,
                    'DonnaJackson12': 5,
                    'KevinMoore98': 5},
    'unit prisoner obvious': {'EmilyThomas54': 2,
                              'SusanJones40': 2,
                              'KennethCastillo64': 1,
                              'MichelleLee80': 2,
                              'BrianWilliams32': 4,
                              'KarenPerez34': 3,
                              'LisaGomez49': 2,
                              'KevinMartin53': 4,
                              'AshleyTrevino10': 4,
                              'StevenAnderson64': 2,
                              'MatthewGonzales10': 4,
                              'JosephSmith26': 1,
                              'ThomasMiller84': 3,
                              'JosephWalker15': 3,
                              'MaryTrevino47': 3,
                              'JosephGutierrez92': 1,
                              'RichardMiller81': 5,
                              'JoshuaHall81': 2,
                              'StevenVasquez67': 5,
                              'AshleyJones61': 2,
                              'MargaretGarza1': 4,
                              'DonnaJackson12': 5,
                              'KevinMoore98': 5},
    'sophisticated invite flee': {'EmilyThomas54': 5,
                                  'KennethCastillo64': 5,
                                  'BrianWilliams32': 5,
                                  'KarenPerez34': 3,
                                  'EdwardHarris8': 5,
                                  'DonnaSmith26': 4,
                                  'LisaGomez49': 5,
                                  'AshleyTrevino10': 2,
                                  'JessicaGarcia99': 5,
                                  'StevenAnderson64': 3,
                                  'MatthewGonzales10': 5,
                                  'AndrewThomas93': 5,
                                  'EmilyMartinez19': 3,
                                  'ThomasMiller84': 1,
                                  'JosephWalker15': 2,
                                  'MaryTrevino47': 4,
                                  'RichardMiller81': 2,
                                  'JessicaGreen37': 1,
                                  'JoshuaHall81': 4,
                                  'StevenVasquez67': 5,
                                  'AshleyJones61': 1,
                                  'DonnaJackson12': 4},
    'venture hunter largely': {'EmilyThomas54': 2,
                               'KennethCastillo64': 5,
                               'BrianWilliams32': 5,
                               'KarenPerez34': 1,
                               'EdwardHarris8': 1,
                               'DonnaSmith26': 1,
                               'KevinMartin53': 1,
                               'JessicaGarcia99': 2,
                               'StevenAnderson64': 1,
                               'MatthewGonzales10': 2,
                               'AndrewThomas93': 3,
                               'EmilyMartinez19': 4,
                               'JosephSmith26': 2,
                               'ThomasMiller84': 2,
                               'JosephWalker15': 1,
                               'MaryTrevino47': 1,
                               'JosephGutierrez92': 5,
                               'JessicaGreen37': 2,
                               'StevenVasquez67': 2,
                               'AshleyJones61': 5,
                               'MargaretGarza1': 4},
    'assumption': {'EmilyThomas54': 1,
                   'SusanJones40': 5,
                   'KennethCastillo64': 5,
                   'MichelleLee80': 5,
                   'BrianWilliams32': 4,
                   'KarenPerez34': 3,
                   'DonnaSmith26': 5,
                   'LisaGomez49': 1,
                   'KevinMartin53': 2,
                   'AshleyTrevino10': 5,
                   'JessicaGarcia99': 2,
                   'StevenAnderson64': 4,
                   'MatthewGonzales10': 5,
                   'StevenScott48': 4,
                   'AndrewThomas93': 2,
                   'EmilyMartinez19': 2,
                   'JosephSmith26': 2,
                   'ThomasMiller84': 5,
                   'JosephWalker15': 2,
                   'JosephGutierrez92': 2,
                   'RichardMiller81': 4,
                   'JessicaGreen37': 3,
                   'JoshuaHall81': 3,
                   'StevenVasquez67': 5,
                   'AshleyJones61': 2,
                   'MargaretGarza1': 2},
    'soil': {'EmilyThomas54': 5,
             'KennethCastillo64': 2,
             'MichelleLee80': 1,
             'BrianWilliams32': 4,
             'EdwardHarris8': 4,
             'DonnaSmith26': 2,
             'LisaGomez49': 2,
             'KevinMartin53': 4,
             'JessicaGarcia99': 5,
             'StevenAnderson64': 5,
             'MatthewGonzales10': 3,
             'StevenScott48': 1,
             'AndrewThomas93': 4,
             'JosephSmith26': 2,
             'ThomasMiller84': 1,
             'JosephWalker15': 2,
             'RichardMiller81': 2,
             'JessicaGreen37': 2,
             'JoshuaHall81': 3,
             'AshleyJones61': 1,
             'MargaretGarza1': 2,
             'DonnaJackson12': 2},
    'hundred bank': {'EmilyThomas54': 3,
                     'SusanJones40': 4,
                     'MichelleLee80': 2,
                     'KarenPerez34': 4,
                     'EdwardHarris8': 4,
                     'DonnaSmith26': 4,
                     'LisaGomez49': 5,
                     'KevinMartin53': 1,
                     'AshleyTrevino10': 2,
                     'JessicaGarcia99': 3,
                     'StevenAnderson64': 3,
                     'MatthewGonzales10': 1,
                     'StevenScott48': 1,
                     'EmilyMartinez19': 2,
                     'JosephSmith26': 2,
                     'ThomasMiller84': 1,
                     'JosephWalker15': 3,
                     'JosephGutierrez92': 1,
                     'RichardMiller81': 5,
                     'JessicaGreen37': 1,
                     'JoshuaHall81': 5,
                     'StevenVasquez67': 1,
                     'AshleyJones61': 4,
                     'MargaretGarza1': 3,
                     'DonnaJackson12': 4,
                     'KevinMoore98': 4},
    'neighbor resort': {'EmilyThomas54': 4,
                        'SusanJones40': 1,
                        'MichelleLee80': 1,
                        'BrianWilliams32': 5,
                        'KarenPerez34': 5,
                        'EdwardHarris8': 3,
                        'DonnaSmith26': 5,
                        'LisaGomez49': 5,
                        'KevinMartin53': 1,
                        'JessicaGarcia99': 5,
                        'StevenAnderson64': 2,
                        'MatthewGonzales10': 5,
                        'AndrewThomas93': 5,
                        'EmilyMartinez19': 3,
                        'JosephSmith26': 2,
                        'ThomasMiller84': 3,
                        'JosephWalker15': 2,
                        'MaryTrevino47': 3,
                        'RichardMiller81': 5,
                        'JoshuaHall81': 5,
                        'AshleyJones61': 2,
                        'DonnaJackson12': 1,
                        'KevinMoore98': 4},
    'million teen feature': {'SusanJones40': 2,
                             'KennethCastillo64': 1,
                             'MichelleLee80': 5,
                             'BrianWilliams32': 4,
                             'KarenPerez34': 2,
                             'EdwardHarris8': 5,
                             'DonnaSmith26': 4,
                             'LisaGomez49': 4,
                             'KevinMartin53': 5,
                             'AshleyTrevino10': 3,
                             'StevenAnderson64': 4,
                             'MatthewGonzales10': 3,
                             'StevenScott48': 4,
                             'AndrewThomas93': 1,
                             'JosephSmith26': 5,
                             'JosephWalker15': 5,
                             'MaryTrevino47': 4,
                             'JosephGutierrez92': 2,
                             'RichardMiller81': 1,
                             'JessicaGreen37': 5,
                             'JoshuaHall81': 5,
                             'StevenVasquez67': 4,
                             'AshleyJones61': 5,
                             'MargaretGarza1': 3,
                             'DonnaJackson12': 5,
                             'KevinMoore98': 3},
    'versus representation': {'SusanJones40': 5,
                              'KennethCastillo64': 2,
                              'MichelleLee80': 5,
                              'BrianWilliams32': 2,
                              'KarenPerez34': 4,
                              'EdwardHarris8': 1,
                              'DonnaSmith26': 3,
                              'LisaGomez49': 4,
                              'KevinMartin53': 5,
                              'AshleyTrevino10': 5,
                              'JessicaGarcia99': 3,
                              'StevenAnderson64': 3,
                              'MatthewGonzales10': 4,
                              'StevenScott48': 1,
                              'AndrewThomas93': 4,
                              'EmilyMartinez19': 4,
                              'JosephSmith26': 4,
                              'JosephWalker15': 1,
                              'MaryTrevino47': 4,
                              'JosephGutierrez92': 3,
                              'RichardMiller81': 3,
                              'JessicaGreen37': 2,
                              'JoshuaHall81': 1,
                              'StevenVasquez67': 5,
                              'MargaretGarza1': 5,
                              'DonnaJackson12': 2,
                              'KevinMoore98': 4},
    'believe welfare': {'EmilyThomas54': 5,
                        'SusanJones40': 5,
                        'KennethCastillo64': 2,
                        'MichelleLee80': 3,
                        'KarenPerez34': 1,
                        'DonnaSmith26': 4,
                        'LisaGomez49': 3,
                        'KevinMartin53': 2,
                        'AshleyTrevino10': 4,
                        'JessicaGarcia99': 5,
                        'StevenAnderson64': 2,
                        'MatthewGonzales10': 1,
                        'AndrewThomas93': 1,
                        'EmilyMartinez19': 4,
                        'JosephSmith26': 3,
                        'JosephWalker15': 5,
                        'MaryTrevino47': 1,
                        'JosephGutierrez92': 1,
                        'JoshuaHall81': 4,
                        'StevenVasquez67': 5,
                        'MargaretGarza1': 5,
                        'DonnaJackson12': 1,
                        'KevinMoore98': 3},
    'eastern least knock wealth': {'EmilyThomas54': 3,
                                   'SusanJones40': 2,
                                   'MichelleLee80': 5,
                                   'BrianWilliams32': 5,
                                   'KarenPerez34': 3,
                                   'DonnaSmith26': 5,
                                   'LisaGomez49': 1,
                                   'KevinMartin53': 1,
                                   'AshleyTrevino10': 4,
                                   'StevenAnderson64': 3,
                                   'MatthewGonzales10': 5,
                                   'StevenScott48': 2,
                                   'AndrewThomas93': 5,
                                   'EmilyMartinez19': 2,
                                   'JosephSmith26': 4,
                                   'ThomasMiller84': 3,
                                   'JosephWalker15': 5,
                                   'MaryTrevino47': 3,
                                   'JessicaGreen37': 3,
                                   'JoshuaHall81': 1,
                                   'StevenVasquez67': 2,
                                   'AshleyJones61': 3,
                                   'MargaretGarza1': 2,
                                   'DonnaJackson12': 5,
                                   'KevinMoore98': 3},
    'he reply suggest': {'EmilyThomas54': 1,
                         'SusanJones40': 1,
                         'MichelleLee80': 5,
                         'BrianWilliams32': 4,
                         'KarenPerez34': 5,
                         'EdwardHarris8': 1,
                         'LisaGomez49': 2,
                         'KevinMartin53': 5,
                         'AshleyTrevino10': 2,
                         'JessicaGarcia99': 5,
                         'StevenAnderson64': 4,
                         'MatthewGonzales10': 2,
                         'StevenScott48': 5,
                         'AndrewThomas93': 4,
                         'EmilyMartinez19': 1,
                         'JosephSmith26': 2,
                         'ThomasMiller84': 1,
                         'JosephWalker15': 5,
                         'MaryTrevino47': 1,
                         'JosephGutierrez92': 3,
                         'RichardMiller81': 4,
                         'JessicaGreen37': 2,
                         'JoshuaHall81': 5,
                         'StevenVasquez67': 4,
                         'AshleyJones61': 5,
                         'MargaretGarza1': 4,
                         'DonnaJackson12': 2,
                         'KevinMoore98': 1}}
