import unittest
import izpit


datoteka = 'public/data/nominacije1.txt'
slovar = {'DIRECTING': ['fvlnokz', 'vwmlaig', 'yreipgb', 'vtzskhd', 'fvliokh', 'ytcenab', 'yrlephz', 'jrvtqkhz', 'tcapgud'], 'WRITING (ADAPTED SCREENPLAY)': ['fvlnokz', 'ynikxz', 'ytcenab', 'jwcqaix'], 'FOREIGN LANGUAGE FILM': ['ynikxz', 'yvtmnou', 'frvtnaix', 'jwcqaix', 'yreipgb', 'fvliokh', 'fvlnokz', 'yrlephz', 'vtzskhd'], 'PRODUCTION DESIGN': ['vtzskhd', 'jrvtqkhz', 'fvlnokz', 'yvtmnou'], 'ACTRESS IN A SUPPORTING ROLE': ['fvliokh', 'jrqesb', 'jwcqaix'], 'ACTOR IN A LEADING ROLE': ['fvliokh', 'fcokuz', 'vtzskhd', 'jqnsuhz', 'ytcenab', 'yreipgb', 'ynikxz', 'tcapgud'], 'MUSIC (ORIGINAL SONG)': ['jqnsuhz', 'fvlnokz', 'yvtmnou', 'ftlpkuhz', 'frvtnaix', 'ytcenab', 'ywqlish'], 'SHORT FILM (LIVE ACTION)': ['jrvtqkhz', 'jrqesb', 'wqensgbk', 'jqnsuhz'], 'ACTRESS IN A LEADING ROLE': ['wqensgbk', 'jrqesb', 'ytcenab', 'jqnsuhz', 'jrvtqkhz', 'vtzskhd'], 'CINEMATOGRAPHY': ['fcokuz', 'yvtmnou', 'vtzskhd', 'fvliokh', 'jqnsuhz', 'frvtnaix', 'tcapgud', 'xmaokuh'], 'WRITING (ORIGINAL SCREENPLAY)': ['tcapgud', 'ywqlish', 'jrvtqkhz', 'fcokuz', 'yvtmnou', 'wqensgbk'], 'VISUAL EFFECTS': ['jrvtqkhz', 'jwcqaix', 'ywqlish', 'ytcenab', 'xmaokuh'], 'SHORT FILM (ANIMATED)': ['jrqesb', 'yreipgb', 'wqensgbk', 'tcapgud', 'fvlnokz'], 'COSTUME DESIGN': ['vwmlaig', 'ytcenab', 'fvliokh'], 'SOUND MIXING': ['vwmlaig', 'jrvtqkhz', 'yreipgb'], 'DOCUMENTARY (SHORT SUBJECT)': ['vtzskhd', 'ywqlish', 'jrvtqkhz', 'fvlnokz', 'ynikxz', 'yreipgb', 'ftlpkuhz', 'frvtnaix', 'jqnsuhz'], 'BEST PICTURE': ['vtzskhd', 'fvlnokz', 'jrvtqkhz', 'yvtmnou', 'ywqlish', 'jwcqaix', 'yreipgb'], 'SOUND EDITING': ['yvtmnou', 'yrlephz', 'ytcenab', 'vwmlaig', 'fvlnokz', 'tcapgud', 'ywqlish', 'jqnsuhz'], 'DOCUMENTARY (FEATURE)': ['vwmlaig', 'jrqesb', 'ftlpkuhz', 'tcapgud'], 'FILM EDITING': ['wqensgbk', 'fvlnokz', 'ytcenab', 'yreipgb', 'fcokuz', 'xmaokuh', 'fvliokh', 'yrlephz'], 'MUSIC (ORIGINAL SCORE)': ['yrlephz', 'vtzskhd', 'jqnsuhz', 'fvlnokz', 'wqensgbk', 'tcapgud'], 'ANIMATED FEATURE FILM': ['ytcenab', 'fvlnokz', 'jrqesb', 'ywqlish', 'yrlephz', 'yvtmnou', 'ynikxz', 'fcokuz'], 'MAKEUP AND HAIRSTYLING': ['yrlephz', 'wqensgbk', 'jrvtqkhz'], 'ACTOR IN A SUPPORTING ROLE': ['xmaokuh', 'jqnsuhz', 'fcokuz', 'frvtnaix', 'fvlnokz', 'yrlephz', 'yreipgb', 'tcapgud', 'jwcqaix']}

test_case = unittest.TestCase()
test_case.maxDiff = None
test_case.assertEqual(izpit.preberi(datoteka), slovar)