DATUMI_TEST = [
    (('05-Aug-1906',), (1906, 8, 5)),
    (('07-Mar-1971',), (1971, 3, 7))
]

DATOTEKA_TEST_1 = "oscars_test.csv"
PODATKI_TEST_1 = [
    ['Lewis Milestone', 'Chisinau', 'Moldova', (1895, 9, 30), 1927, 'Best Director', 'Two Arabian Knights'],
    ['Frank Lloyd', 'Glasgow', 'Scotland', (1886, 2, 2), 1930, 'Best Director', 'The Divine Lady'],
    ['Lewis Milestone', 'Chisinau', 'Moldova', (1895, 9, 30), 1931, 'Best Director', 'All Quiet on the Western Front']
]

PRIMERJAVE_TEST_1 = [
    [((2008, 4, 12), (2008, 2, 12)), False],
    [((2001, 4, 12), (2008, 2, 12)), True],
    [((2001, 4, 12), (2001, 4, 12)), True]
]

PRIMERJAVE_TEST_2 = [
    [((2008, 4, 12), (2009, 4, 12)), True],
    [((2008, 4, 12), (2008, 5, 12)), True],
    [((2008, 4, 12), (2008, 4, 13)), True],
    [((2008, 4, 12), (2008, 4, 12)), True],
    [((2009, 4, 12), (2008, 4, 12)), False],
    [((2008, 5, 12), (2008, 4, 12)), False],
    [((2008, 4, 13), (2008, 4, 12)), False],
]

DATOTEKA_TEST_2 = "oscars.csv"
PODATKI_TEST_2 = [
    ['Lewis Milestone', 'Chisinau', 'Moldova', (1895, 9, 30), 1927, 'Best Director', 'Two Arabian Knights'],
    ['Frank Lloyd', 'Glasgow', 'Scotland', (1886, 2, 2), 1930, 'Best Director', 'The Divine Lady'],
    ['Lewis Milestone', 'Chisinau', 'Moldova', (1895, 9, 30), 1931, 'Best Director', 'All Quiet on the Western Front'],
    ['Norman Taurog', 'Chicago', 'USA', (1899, 2, 23), 1932, 'Best Director', 'Skippy'],
    ['Frank Borzage', 'Salt Lake City', 'USA', (1894, 4, 23), 1933, 'Best Director', 'Bad Girl'],
    ['Frank Lloyd', 'Glasgow', 'Scotland', (1886, 2, 2), 1934, 'Best Director', 'Cavalcade'],
    ['Frank Capra', 'Bisacquino', 'Italy', (1897, 5, 18), 1935, 'Best Director', 'It Happened One Night'],
    ['John Ford', 'Cape Elizabeth', 'USA', (1894, 2, 1), 1936, 'Best Director', 'The Informer'],
    ['Frank Capra', 'Bisacquino', 'Italy', (1897, 5, 18), 1937, 'Best Director', 'Mr. Deeds Goes to Town'],
    ['Leo McCarey', 'Los Angeles', 'USA', (1898, 10, 3), 1938, 'Best Director', 'The Awful Truth'],
    ['Frank Capra', 'Bisacquino', 'Italy', (1897, 5, 18), 1939, 'Best Director', "You Can't Take It with You"],
    ['Victor Fleming', 'Pasadena', 'USA', (1883, 2, 23), 1940, 'Best Director', 'Gone with the Wind'],
    ['John Ford', 'Cape Elizabeth', 'USA', (1894, 2, 1), 1941, 'Best Director', 'The Grapes of Wrath'],
    ['John Ford', 'Cape Elizabeth', 'USA', (1894, 2, 1), 1942, 'Best Director', 'How Green Was My Valley'],
    ['William Wyler', 'Mulhouse', 'France', (1902, 7, 1), 1943, 'Best Director', 'Mrs. Miniver'],
    ['Michael Curtiz', 'Budapest', 'Hungary', (1886, 12, 24), 1944, 'Best Director', 'Casablanca'],
    ['Leo McCarey', 'Los Angeles', 'USA', (1898, 10, 3), 1945, 'Best Director', 'Going My Way'],
    ['Jerome Robbins', 'New York City', 'USA', (1918, 10, 11), 1962, 'Best Director', 'West Side Story'],
    ['Billy Wilder', 'Sucha', 'Austria', (1906, 6, 22), 1946, 'Best Director', 'The Lost Weekend'],
    ['William Wyler', 'Mulhouse', 'France', (1902, 7, 1), 1947, 'Best Director', 'The Best Years of Our Lives'],
    ['Elia Kazan', 'Istanbul', 'Turkey', (1909, 9, 7), 1948, 'Best Director', "Gentleman's Agreement"],
    ['John Huston', 'Nevada', 'USA', (1906, 8, 5), 1949, 'Best Director', 'The Treasure of the Sierra Madre'],
    ['Joseph L. Mankiewicz', 'Wilkes-Barre', 'USA', (1909, 2, 11), 1950, 'Best Director', 'A Letter to Three Wives'],
    ['Joseph L. Mankiewicz', 'Wilkes-Barre', 'USA', (1909, 2, 11), 1951, 'Best Director', 'All About Eve'],
    ['George Stevens', 'Oakland', 'USA', (1904, 12, 18), 1952, 'Best Director', 'A Place in the Sun'],
    ['John Ford', 'Cape Elizabeth', 'USA', (1894, 2, 1), 1953, 'Best Director', 'The Quiet Man'],
    ['Fred Zinnemann', 'Vienna', 'Austria', (1907, 4, 29), 1954, 'Best Director', 'From Here to Eternity'],
    ['Elia Kazan', 'Istanbul', 'Turkey', (1909, 9, 7), 1955, 'Best Director', 'On the Waterfront'],
    ['Delbert Mann', 'Lawrence', 'USA', (1920, 1, 30), 1956, 'Best Director', 'Marty'],
    ['George Stevens', 'Oakland', 'USA', (1904, 12, 18), 1957, 'Best Director', 'Giant'],
    ['David Lean', 'Croydon', 'England', (1908, 3, 25), 1958, 'Best Director', 'The Bridge on the River Kwai'],
    ['Vincente Minnelli', 'Chicago', 'USA', (1903, 2, 28), 1959, 'Best Director', 'Gigi'],
    ['William Wyler', 'Mulhouse', 'France', (1902, 7, 1), 1960, 'Best Director', 'Ben-Hur'],
    ['Billy Wilder', 'Sucha', 'Austria', (1906, 6, 22), 1961, 'Best Director', 'The Apartment'],
    ['Robert Wise', 'Winchester', 'USA', (1914, 9, 10), 1962, 'Best Director', 'West Side Story'],
    ['David Lean', 'Croydon', 'England', (1908, 3, 25), 1963, 'Best Director', 'Lawrence of Arabia'],
    ['Tony Richardson', 'Shipley', 'England', (1928, 6, 5), 1964, 'Best Director', 'Tom Jones'],
    ['George Cukor', 'New York City', 'USA', (1899, 7, 7), 1965, 'Best Director', 'My Fair Lady'],
    ['Robert Wise', 'Winchester', 'USA', (1914, 9, 10), 1966, 'Best Director', 'The Sound of Music'],
    ['Fred Zinnemann', 'Vienna', 'Austria', (1907, 4, 29), 1967, 'Best Director', 'A Man for All Seasons'],
    ['Mike Nichols', 'Berlin', 'Germany', (1931, 11, 6), 1968, 'Best Director', 'The Graduate'],
    ['Joel Coen', 'St. Louis Park', 'USA', (1954, 11, 29), 2008, 'Best Director', 'No Country for Old Men'],
    ['Carol Reed', 'London', 'England', (1906, 12, 30), 1969, 'Best Director', 'Oliver!'],
    ['John Schlesinger', 'London', 'England', (1926, 2, 16), 1969, 'Best Director', 'Midnight Cowboy'],
    ['Franklin J. Schaffner', 'Tokyo', 'Japan', (1920, 5, 30), 1970, 'Best Director', 'Patton'],
    ['William Friedkin', 'Chicago', 'USA', (1935, 8, 29), 1972, 'Best Director', 'The French Connection'],
    ['Bob Fosse', 'Chicago', 'USA', (1927, 6, 23), 1973, 'Best Director', 'Cabaret'],
    ['George Roy Hill', 'Minneapolis', 'USA', (1921, 12, 20), 1973, 'Best Director', 'The Sting'],
    ['Francis Ford Coppola', 'Detroit', 'USA', (1939, 4, 7), 1975, 'Best Director', 'The Godfather Part II'],
    ['Milos Forman', 'Čáslav', 'USA', (1932, 2, 18), 1976, 'Best Director', "One Flew over the Cuckoo's Nest"],
    ['John G. Avildsen', 'Oak Park', 'USA', (1935, 12, 21), 1976, 'Best Director', 'Rocky'],
    ['Woody Allen', 'Brooklyn', 'USA', (1935, 12, 1), 1978, 'Best Director', 'Annie Hall'],
    ['Michael Cimino', 'New York City', 'USA', (1939, 2, 3), 1979, 'Best Director', 'The Deer Hunter'],
    ['Robert Benton', 'Waxahachie', 'USA', (1932, 9, 29), 1980, 'Best Director', 'Kramer vs. Kramer'],
    ['Robert Redford', 'Santa Monica', 'USA', (1936, 8, 18), 1980, 'Best Director', 'Ordinary People'],
    ['Warren Beatty', 'Richmond', 'USA', (1937, 3, 30), 1981, 'Best Director', 'Reds'],
    ['Richard Attenborough', 'Cambridge', 'England', (1923, 8, 29), 1982, 'Best Director', 'Gandhi'],
    ['James L. Brooks', 'North Bergen', 'USA', (1940, 5, 9), 1983, 'Best Director', 'Terms of Endearment'],
    ['Milos Forman', 'Čáslav', 'USA', (1932, 2, 18), 1985, 'Best Director', 'Amadeus'],
    ['Sydney Pollack', 'Lafayette', 'USA', (1934, 7, 1), 1986, 'Best Director', 'Out of Africa'],
    ['Oliver Stone', 'New York City', 'USA', (1946, 9, 15), 1990, 'Best Director', 'Platoon'],
    ['Bernardo Bertolucci', 'Parma', 'Italy', (1941, 3, 16), 1988, 'Best Director', 'The Last Emperor'],
    ['Barry Levinson', 'Baltimore', 'USA', (1942, 4, 6), 1989, 'Best Director', 'Rain Man'],
    ['Oliver Stone', 'New York City', 'USA', (1946, 9, 15), 1990, 'Best Director', 'Born on the Fourth of July'],
    ['Kevin Costner', 'Lynwood', 'USA', (1955, 1, 18), 1991, 'Best Director', 'Dances with Wolves'],
    ['Jonathan Demme', 'Baldwin', 'USA', (1944, 2, 22), 1992, 'Best Director', 'The Silence of the Lambs'],
    ['Clint Eastwood', 'San Francisco', 'USA', (1930, 5, 31), 1993, 'Best Director', 'Unforgiven'],
    ['Steven Spielberg', 'Cincinnati', 'USA', (1946, 12, 18), 1994, 'Best Director', "Schindler's List"],
    ['Robert Zemeckis', 'Chicago', 'USA', (1952, 5, 14), 1995, 'Best Director', 'Forrest Gump'],
    ['Mel Gibson', 'Peekskill', 'USA', (1956, 1, 3), 1996, 'Best Director', 'Braveheart'],
    ['Anthony Minghella', 'Ryde', 'England', (1954, 1, 6), 1997, 'Best Director', 'The English Patient'],
    ['James Cameron', 'Kapuskasing', 'Canada', (1954, 8, 16), 1998, 'Best Director', 'Titanic'],
    ['Steven Spielberg', 'Cincinnati', 'USA', (1946, 12, 18), 1999, 'Best Director', 'Saving Private Ryan'],
    ['Sam Mendes', 'Reading', 'England', (1965, 8, 1), 2000, 'Best Director', 'American Beauty'],
    ['Steven Soderbergh', 'Atlanta', 'USA', (1963, 1, 14), 2001, 'Best Director', 'Traffic'],
    ['Ron Howard', 'Duncan', 'USA', (1954, 3, 1), 2002, 'Best Director', 'A Beautiful Mind'],
    ['Roman Polanski', 'Paris', 'France', (1933, 8, 18), 2003, 'Best Director', 'The Pianist'],
    ['Peter Jackson', 'Wellington', 'New Zealand', (1961, 10, 31), 2004, 'Best Director',
     'The Lord of the Rings: Return of the King'],
    ['Clint Eastwood', 'San Francisco', 'USA', (1930, 5, 31), 2005, 'Best Director', 'Million Dollar Baby'],
    ['Ang Lee', 'Pingtung', 'Taiwan', (1954, 10, 23), 2006, 'Best Director', 'Brokeback Mountain'],
    ['Martin Scorsese', 'Flushing', 'USA', (1942, 11, 17), 2007, 'Best Director', 'The Departed'],
    ['Ethan Coen', 'St. Louis Park', 'USA', (1957, 9, 21), 2008, 'Best Director', 'No Country for Old Men'],
    ['Danny Boyle', 'Manchester', 'England', (1956, 10, 20), 2009, 'Best Director', 'Slumdog Millionaire'],
    ['Kathryn Bigelow', 'San Carlos', 'USA', (1951, 11, 27), 2009, 'Best Director', 'The Hurt Locker'],
    ['Michel Hazanavicius', 'Paris', 'France', (1967, 3, 29), 2012, 'Best Director', 'The Artist'],
    ['Ang Lee', 'Pingtung', 'Taiwan', (1954, 10, 23), 2013, 'Best Director', 'Life of Pi'],
    ['Emil Jannings', 'Rorschach', 'Switzerland', (1884, 7, 23), 1929, 'Best Actor', 'The Last Command'],
    ['Warner Baxter', 'Columbus', 'USA', (1889, 3, 29), 1930, 'Best Actor', 'In Old Arizona'],
    ['George Arliss', 'London', 'England', (1868, 4, 10), 1930, 'Best Actor', 'Desraeli'],
    ['Lionel Barrymore', 'Philadelphia', 'USA', (1878, 4, 28), 1931, 'Best Actor', 'A Free Soul'],
    ['Wallace Beery', 'Kansas City', 'USA', (1885, 4, 1), 1932, 'Best Actor', 'The Champ'],
    ['Charles Laughton', 'Victoria Hotel', 'England', (1899, 7, 1), 1934, 'Best Actor',
     'The Private Life of Henry VIII'],
    ['Clark Gable', 'Cadiz', 'USA', (1901, 2, 1), 1935, 'Best Actor', 'It Happened One Night'],
    ['Victor McLaglen', 'Tunbridge Wells', 'England', (1883, 12, 11), 1936, 'Best Actor', 'The Informer'],
    ['Paul Muni', 'Lviv', 'Ukraine', (1895, 9, 22), 1937, 'Best Actor', 'The Story of Louis Pasteur'],
    ['Spencer Tracy', 'Milwaukee', 'USA', (1900, 4, 5), 1938, 'Best Actor', 'Captains Courageous'],
    ['Spencer Tracy', 'Milwaukee', 'USA', (1900, 4, 5), 1939, 'Best Actor', 'Boys Town'],
    ['Robert Donat', 'Withington', 'England', (1905, 3, 18), 1940, 'Best Actor', 'Goodbye Mr. Chips'],
    ['Jimmy Stewart', 'Indiana', 'USA', (1908, 5, 20), 1941, 'Best Actor', 'The Philadelphia Story'],
    ['Gary Cooper', 'Helena', 'USA', (1901, 5, 7), 1942, 'Best Actor', 'Sergeant York'],
    ['James Cagney', 'Manhattan', 'USA', (1899, 7, 17), 1943, 'Best Actor', 'Yankee Doodle Dandy'],
    ['Paul Lukas', 'Budapest', 'Hungary', (1887, 5, 26), 1944, 'Best Actor', 'Watch on the Rhine'],
    ['Bing Crosby', 'Tacoma', 'USA', (1903, 5, 3), 1945, 'Best Actor', 'Going My Way'],
    ['Ray Milland', 'Neath', 'Wales', (1907, 1, 3), 1946, 'Best Actor', 'The Lost Weekend'],
    ['Fredric March', 'Racine', 'USA', (1897, 8, 31), 1947, 'Best Actor', 'The Best Years of Our Lives'],
    ['Ronald Colman', 'Richmond', 'England', (1891, 2, 9), 1948, 'Best Actor', 'A Double Life'],
    ['Laurence Olivier', 'Dorking', 'England', (1907, 5, 22), 1949, 'Best Actor', 'Hamlet'],
    ['Broderick Crawford', 'Philadelphia', 'USA', (1911, 12, 9), 1950, 'Best Actor', "All The King's Men"],
    ['Jose Ferrer', 'Santurce', 'Puerto Rico', (1909, 1, 8), 1951, 'Best Actor', 'Cyrano de Bergerac'],
    ['Humphrey Bogart', 'New York City', 'USA', (1899, 12, 25), 1952, 'Best Actor', 'The Africa Queen'],
    ['Gary Cooper', 'Helena', 'USA', (1901, 5, 7), 1953, 'Best Actor', 'High Noon'],
    ['William Holden', "O'fallon", 'USA', (1918, 4, 17), 1954, 'Best Actor', 'Stalag 17'],
    ['Marlon Brando', 'Omaha', 'USA', (1924, 4, 3), 1955, 'Best Actor', 'On the Waterfront'],
    ['Ernest Borgnine', 'Hamden', 'USA', (1917, 1, 24), 1956, 'Best Actor', 'Marty'],
    ['Yul Brynner', 'Vladivostok', 'Russia', (1920, 7, 11), 1957, 'Best Actor', 'The King and I'],
    ['Alec Guinness', 'London', 'England', (1914, 4, 2), 1958, 'Best Actor', 'The Bridge on the River Kwai'],
    ['David Niven', 'London', 'England', (1909, 3, 1), 1959, 'Best Actor', 'Separate Tables'],
    ['Charlton Heston', 'Evanston', 'USA', (1923, 10, 4), 1960, 'Best Actor', 'Ben-hur'],
    ['Burt Lancaster', 'New York City', 'USA', (1913, 11, 2), 1961, 'Best Actor', 'Elmer Gantry'],
    ['Maximilian Schell', 'Vienna', 'Austria', (1930, 12, 8), 1962, 'Best Actor', 'Judgement at Nuremberg'],
    ['Gregory Peck', 'La Jolla', 'USA', (1916, 4, 5), 1963, 'Best Actor', 'To Kill a Mockingbird'],
    ['Sidney Poitier', 'Miami', 'USA', (1927, 2, 20), 1964, 'Best Actor', 'Lilies of the Field'],
    ['Rex Harrison', 'Huyton', 'England', (1908, 3, 5), 1965, 'Best Actor', 'My Fair Lady'],
    ['Lee Marvin', 'New York City', 'USA', (1924, 2, 19), 1966, 'Best Actor', 'Cat Ballou'],
    ['Paul Scofield', 'Hurstpierpoint', 'England', (1922, 1, 21), 1967, 'Best Actor', 'A Man For All Seasons'],
    ['Rod Steiger', 'Westhampton', 'USA', (1925, 4, 14), 1968, 'Best Actor', 'In the Heat of the Night'],
    ['Cliff Robertson', 'La Jolla', 'USA', (1923, 9, 9), 1969, 'Best Actor', 'Charly'],
    ['John Wayne', 'Winterset', 'USA', (1907, 5, 26), 1970, 'Best Actor', 'True Grit'],
    ['George C. Scott', 'Wise', 'USA', (1927, 10, 18), 1971, 'Best Actor', 'Patton'],
    ['Gene Hackman', 'San Bernardino', 'USA', (1930, 1, 30), 1972, 'Best Actor', 'The French Connection'],
    ['Marlon Brando', 'Omaha', 'USA', (1924, 4, 3), 1973, 'Best Actor', 'The Godfather'],
    ['Jack Lemmon', 'Newton', 'USA', (1925, 2, 8), 1974, 'Best Actor', 'Save the Tiger'],
    ['Art Carney', 'Mount Vernon', 'USA', (1918, 11, 4), 1975, 'Best Actor', 'Harry and Tonto'],
    ['Jack Nicholson', 'New York City', 'USA', (1937, 4, 22), 1976, 'Best Actor', "One Flew Over the Cuckoo's Nest"],
    ['Peter Finch', 'South Kensington', 'England', (1916, 9, 28), 1977, 'Best Actor', 'Network'],
    ['Richard Dreyfuss', 'Brooklyn', 'USA', (1947, 10, 29), 1978, 'Best Actor', 'The Goodbye Girl'],
    ['Jon Voight', 'Yonkers', 'USA', (1938, 12, 29), 1979, 'Best Actor', 'Coming Home'],
    ['Dustin Hoffman', 'Los Angeles', 'USA', (1937, 8, 8), 1980, 'Best Actor', 'Kramer vs. Kramer'],
    ['Robert De Niro', 'New York City', 'USA', (1943, 8, 17), 1981, 'Best Actor', 'Raging Bull'],
    ['Henry Fonda', 'Grand Island', 'USA', (1905, 5, 16), 1982, 'Best Actor', 'On Golden Pond'],
    ['Ben Kingsley', 'Scarborough', 'England', (1943, 12, 31), 1983, 'Best Actor', 'Gandhi'],
    ['Robert Duvall', 'San Diego', 'USA', (1931, 1, 5), 1984, 'Best Actor', 'Tender Mercies'],
    ['F. Murray Abraham', 'Pittsburgh', 'USA', (1939, 10, 24), 1985, 'Best Actor', 'Amadeus'],
    ['William Hurt', 'Washington', 'USA', (1950, 3, 20), 1986, 'Best Actor', 'Kiss of the Spider Woman'],
    ['Paul Newman', 'Shaker Heights', 'USA', (1925, 1, 26), 1987, 'Best Actor', 'The Color of Money'],
    ['Michael Douglas', 'New Brunswick', 'USA', (1944, 9, 25), 1988, 'Best Actor', 'Wall Street'],
    ['Dustin Hoffman', 'Los Angeles', 'USA', (1937, 8, 8), 1989, 'Best Actor', 'Rainman'],
    ['Daniel Day-Lewis', 'London', 'England', (1957, 4, 29), 1990, 'Best Actor', 'My Left Foot'],
    ['Jeremy Irons', 'Cowes', 'England', (1948, 9, 19), 1991, 'Best Actor', 'Reversal of Fortune'],
    ['Anthony Hopkins', 'Port Talbot', 'Wales', (1937, 12, 31), 1992, 'Best Actor', 'Silence of the Lambs'],
    ['Al Pacino', 'East Harlem', 'USA', (1940, 4, 25), 1993, 'Best Actor', 'Scent of a Woman'],
    ['Tom Hanks', 'Concord', 'USA', (1956, 7, 9), 1994, 'Best Actor', 'Philadelphia'],
    ['Tom Hanks', 'Concord', 'USA', (1956, 7, 9), 1995, 'Best Actor', 'Forrest Gump'],
    ['Nicolas Cage', 'Long Beach', 'USA', (1964, 1, 7), 1996, 'Best Actor', 'Leaving Las Vegas'],
    ['Geoffrey Rush', 'Toowoomba', 'Australia', (1951, 7, 6), 1997, 'Best Actor', 'Shine'],
    ['Jack Nicholson', 'New York City', 'USA', (1937, 4, 22), 1997, 'Best Actor', 'As Good as It Gets'],
    ['Roberto Benigni', 'Misericordia', 'Italy', (1952, 10, 27), 1999, 'Best Actor', 'Life is Beautiful'],
    ['Kevin Spacey', 'South Orange', 'USA', (1959, 7, 26), 2000, 'Best Actor', 'American Beauty'],
    ['Russell Crowe', 'Wellington', 'New Zealand', (1964, 4, 7), 2001, 'Best Actor', 'Gladiator'],
    ['Denzel Washington', 'Mount Vernon', 'USA', (1954, 12, 28), 2002, 'Best Actor', 'Training Day'],
    ['Adrien Brody', 'New York City', 'USA', (1973, 4, 14), 2003, 'Best Actor', 'The Pianist'],
    ['Sean Penn', 'Burbank', 'USA', (1960, 8, 17), 2003, 'Best Actor', 'Mystic River'],
    ['Jamie Foxx', 'Terrell', 'USA', (1967, 12, 13), 2005, 'Best Actor', 'Ray'],
    ['Philip Seymour Hoffman', 'Fairport', 'USA', (1967, 7, 23), 2006, 'Best Actor', 'Capote'],
    ['Forest Whitaker', 'Longview', 'USA', (1961, 7, 15), 2007, 'Best Actor', 'The Last King of Scotland'],
    ['Daniel Day-Lewis', 'London', 'England', (1957, 4, 29), 2008, 'Best Actor', 'There Will Be Blood'],
    ['Sean Penn', 'Burbank', 'USA', (1960, 8, 17), 2009, 'Best Actor', 'Milk'],
    ['Jeff Bridges', 'Los Angeles', 'USA', (1949, 12, 4), 2010, 'Best Actor', 'Crazy Heart'],
    ['Colin Firth', 'Grayshott', 'England', (1960, 9, 10), 2011, 'Best Actor', "The King's Speech"],
    ['Jean Dujardin', 'Rueil-Malmaison', 'France', (1972, 6, 19), 2012, 'Best Actor', 'The Artist'],
    ['Daniel Day-Lewis', 'London', 'England', (1957, 4, 29), 2013, 'Best Actor', 'Lincoln'],
    ['Matthew McConaughey', 'Uvalde', 'USA', (1969, 11, 4), 2014, 'Best Actor', 'Dallas Buyers Club'],
    ['Walter Brennan', 'Swampscott', 'USA', (1894, 7, 25), 1938, 'Best Supporting Actor', 'Come and Get It'],
    ['Joseph Schildkraut', 'Vienna', 'Austria', (1896, 3, 22), 1938, 'Best Supporting Actor', 'The Life of Emile Zola'],
    ['Walter Brennan', 'Swampscott', 'USA', (1894, 7, 25), 1939, 'Best Supporting Actor', 'Kentucky'],
    ['Thomas Mitchell', 'Elizabeth', 'USA', (1892, 7, 11), 1940, 'Best Supporting Actor', 'Stagecoach'],
    ['Walter Brennan', 'Swampscott', 'USA', (1894, 7, 25), 1941, 'Best Supporting Actor', 'The Westerner'],
    ['Donald Crisp', 'London', 'England', (1880, 7, 27), 1942, 'Best Supporting Actor', 'How Green Was My Valley'],
    ['Van Heflin', 'Walters', 'USA', (1910, 12, 13), 1943, 'Best Supporting Actor', 'Johnny Eager'],
    ['Charles Coburn', 'Savannah', 'USA', (1877, 6, 17), 1944, 'Best Supporting Actor', 'The More the Merrier'],
    ['Barry Fitzgerald', 'Dublin', 'Ireland', (1888, 3, 10), 1945, 'Best Supporting Actor', 'Going My Way'],
    ['James Dunn', 'New York City', 'USA', (1901, 11, 2), 1946, 'Best Supporting Actor', 'A Tree Grows in Brooklyn'],
    ['Harold Russell', 'North Sydney', 'Canada', (1914, 1, 14), 1947, 'Best Supporting Actor',
     'The Best Years of Our Lives'],
    ['Edmund Gwenn', 'Vale of Glamorgan', 'Wales', (1875, 9, 26), 1948, 'Best Supporting Actor',
     'Miracle on 34th Street'], ['Walter Huston', 'Toronto', 'Canada', (1884, 4, 6), 1949, 'Best Supporting Actor',
                                 'The Treasure of the Sierra Madre'],
    ['Dean Jagger', 'Lima', 'USA', (1903, 11, 7), 1950, 'Best Supporting Actor', "Twelve O'Clock High"],
    ['George Sanders', 'St. Petersburg', 'Russia', (1906, 7, 3), 1951, 'Best Supporting Actor', 'All About Eve'],
    ['Karl Malden', 'Chicago', 'USA', (1912, 3, 22), 1952, 'Best Supporting Actor', 'A Streetcar Named Desire'],
    ['Anthony Quinn', 'Chihuahua', 'Mexico', (1915, 4, 21), 1953, 'Best Supporting Actor', 'Viva Zapata!'],
    ['Frank Sinatra', 'Hoboken', 'USA', (1915, 12, 12), 1954, 'Best Supporting Actor', 'From Here to Eternity'],
    ["Edmond O'Brien", 'New York City', 'USA', (1915, 9, 10), 1955, 'Best Supporting Actor', 'The Barefoot Contessa'],
    ['Jack Lemmon', 'Newton', 'USA', (1925, 2, 8), 1956, 'Best Supporting Actor', 'Mister Roberts'],
    ['Anthony Quinn', 'Chihuahua', 'Mexico', (1915, 4, 21), 1957, 'Best Supporting Actor', 'Lust for Life'],
    ['Red Buttons', 'New York City', 'USA', (1919, 2, 5), 1958, 'Best Supporting Actor', 'Sayonara'],
    ['Burl Ives', 'Hunt City', 'USA', (1909, 6, 14), 1959, 'Best Supporting Actor', 'The Big Country'],
    ['Hugh Griffith', 'Marian Glas', 'Wales', (1912, 5, 30), 1960, 'Best Supporting Actor', 'Ben-Hur'],
    ['Peter Ustinov', 'London', 'England', (1921, 4, 16), 1961, 'Best Supporting Actor', 'Spartacus'],
    ['George Chakiris', 'Norwood', 'USA', (1934, 9, 16), 1962, 'Best Supporting Actor', 'West Side Story'],
    ['Ed Begley, Sr.', 'Hartford', 'USA', (1901, 3, 25), 1963, 'Best Supporting Actor', 'Sweet Bird of Youth'],
    ['Melvyn Douglas', 'Macon', 'USA', (1901, 4, 5), 1964, 'Best Supporting Actor', 'Hud'],
    ['Peter Ustinov', 'London', 'England', (1921, 4, 16), 1965, 'Best Supporting Actor', 'Topkapi'],
    ['Martin Balsam', 'Bronx', 'USA', (1919, 11, 4), 1966, 'Best Supporting Actor', 'A Thousand Clowns'],
    ['Walter Matthau', 'New York City', 'USA', (1920, 10, 1), 1967, 'Best Supporting Actor', 'The Fortune Cookie'],
    ['George Kennedy', 'New York City', 'USA', (1925, 2, 18), 1968, 'Best Supporting Actor', 'Cool Hand Luke'],
    ['Jack Albertson', 'Malden', 'USA', (1907, 6, 16), 1969, 'Best Supporting Actor', 'The Subject Was Roses'],
    ['Gig Young', 'St. Cloud', 'USA', (1913, 11, 4), 1970, 'Best Supporting Actor', "They Shoot Horses, Don't They?"],
    ['John Mills', 'Felixstowe', 'England', (1908, 2, 22), 1971, 'Best Supporting Actor', "Ryan's Daughter"],
    ['Ben Johnson', 'Shidler', 'USA', (1918, 6, 13), 1972, 'Best Supporting Actor', 'The Last Picture Show'],
    ['Joel Grey', 'Cleveland', 'USA', (1932, 4, 11), 1973, 'Best Supporting Actor', 'Cabaret'],
    ['John Houseman', 'Bucharest', 'Romania', (1902, 9, 22), 1974, 'Best Supporting Actor', 'The Paper Chase'],
    ['Robert De Niro', 'New York City', 'USA', (1943, 8, 17), 1975, 'Best Supporting Actor', 'The Godfather Part II'],
    ['George Burns', 'New York City', 'USA', (1896, 1, 20), 1976, 'Best Supporting Actor', 'The Sunshine Boys'],
    ['Jason Robards', 'Chicago', 'USA', (1922, 7, 26), 1977, 'Best Supporting Actor', "All the President's Men"],
    ['Jason Robards', 'Chicago', 'USA', (1922, 7, 26), 1978, 'Best Supporting Actor', 'Julia'],
    ['Christopher Walken', 'Astoria', 'USA', (1943, 3, 31), 1979, 'Best Supporting Actor', 'The Deer Hunter'],
    ['Melvyn Douglas', 'Macon', 'USA', (1901, 4, 5), 1980, 'Best Supporting Actor', 'Being There'],
    ['Timothy Hutton', 'Malibu', 'USA', (1960, 8, 16), 1981, 'Best Supporting Actor', 'Oridnary People'],
    ['John Gielgud', 'London', 'England', (1904, 4, 14), 1982, 'Best Supporting Actor', 'Arthur'],
    ['Lou Gossett, Jr.', 'Brooklyn', 'USA', (1936, 5, 27), 1983, 'Best Supporting Actor', 'An Officer and a Gentleman'],
    ['Jack Nicholson', 'New York City', 'USA', (1937, 4, 22), 1984, 'Best Supporting Actor', 'Terms of Endearment'],
    ['Haing S. Ngor', 'Samrong Young', 'Cambodia', (1940, 3, 22), 1985, 'Best Supporting Actor', 'The Killing Fields'],
    ['Don Ameche', 'Kenosha', 'USA', (1904, 5, 31), 1986, 'Best Supporting Actor', 'Cocoon'],
    ['Michael Caine', 'Bermondsey', 'England', (1933, 3, 14), 1987, 'Best Supporting Actor', 'Hannah and Her Sisters'],
    ['Sean Connery', 'Edinburgh', 'Scotland', (1930, 8, 25), 1988, 'Best Supporting Actor', 'The Untouchables'],
    ['Kevin Kline', 'St. Louis', 'USA', (1947, 10, 24), 1989, 'Best Supporting Actor', 'A Fish Called Wanda'],
    ['Denzel Washington', 'Mount Vernon', 'USA', (1954, 12, 28), 1990, 'Best Supporting Actor', 'Glory'],
    ['Joe Pesci', 'Newark', 'USA', (1943, 2, 9), 1991, 'Best Supporting Actor', 'Good Fellas'],
    ['Jack Palance', 'Lattimer Mines', 'USA', (1919, 2, 18), 1992, 'Best Supporting Actor', 'City Slickers'],
    ['Gene Hackman', 'San Bernardino', 'USA', (1930, 1, 30), 1993, 'Best Supporting Actor', 'Unforgiven'],
    ['Tommy Lee Jones', 'San Saba', 'USA', (1946, 9, 15), 1994, 'Best Supporting Actor', 'The Fugitive'],
    ['Martin Landau', 'Brooklyn', 'USA', (1931, 6, 20), 1995, 'Best Supporting Actor', 'Ed Wood'],
    ['Kevin Spacey', 'South Orange', 'USA', (1959, 7, 26), 1996, 'Best Supporting Actor', 'The Usual Suspects'],
    ['Cuba Gooding, Jr.', 'Bronx', 'USA', (1968, 1, 2), 1997, 'Best Supporting Actor', 'Jerry Maguire'],
    ['Robin Williams', 'Chicago', 'USA', (1951, 7, 21), 1998, 'Best Supporting Actor', 'Good Will Hunting'],
    ['James Coburn', 'Laurel', 'USA', (1928, 8, 31), 1999, 'Best Supporting Actor', 'Affliction'],
    ['Michael Caine', 'Bermondsey', 'England', (1933, 3, 14), 2000, 'Best Supporting Actor', 'The Cider House Rules'],
    ['Benicio Del Toro', 'Santurce', 'Puerto Rico', (1967, 2, 19), 2001, 'Best Supporting Actor', 'Traffic'],
    ['Jim Broadbent', 'Lincoln', 'England', (1949, 5, 24), 2002, 'Best Supporting Actor', 'Iris'],
    ['Chris Cooper', 'Kansas City', 'USA', (1951, 7, 9), 2003, 'Best Supporting Actor', 'Adaptation'],
    ['Tim Robbins', 'West Covina', 'USA', (1958, 10, 16), 2004, 'Best Supporting Actor', 'Mystic River'],
    ['Morgan Freeman', 'Memphis', 'USA', (1937, 6, 1), 2005, 'Best Supporting Actor', 'Million Dollar Baby'],
    ['George Clooney', 'Lexington', 'USA', (1961, 5, 6), 2006, 'Best Supporting Actor', 'Syriana'],
    ['Alan Arkin', 'Brooklyn', 'USA', (1934, 3, 26), 2007, 'Best Supporting Actor', 'Little Miss Sunshine'],
    ['Javier Bardem', 'Las Palmas De Gran Canaria', 'Canary Islands', (1969, 3, 1), 2008, 'Best Supporting Actor',
     'No Country for Old Men'],
    ['Heath Ledger', 'Perth', 'Australia', (1979, 4, 4), 2009, 'Best Supporting Actor', 'The Dark Knight'],
    ['Christoph Waltz', 'Na', 'USA', (1956, 10, 4), 2010, 'Best Supporting Actor', 'Inglourious Basterds'],
    ['Christian Bale', 'Haverfordwest', 'Wales', (1974, 1, 30), 2011, 'Best Supporting Actor', 'The Fighter'],
    ['Christopher Plummer', 'Toronto', 'Canada', (1929, 12, 13), 2012, 'Best Supporting Actor', 'Beginning'],
    ['Christoph Waltz', 'Na', 'USA', (1956, 10, 4), 2013, 'Best Supporting Actor', 'Django Unchained'],
    ['Jared Leto', 'Bossier City', 'USA', (1971, 12, 26), 2014, 'Best Supporting Actor', 'Dallas Buyers Club'],
    ['Janet Gaynor', 'Philadelphia', 'USA', (1906, 10, 6), 1929, 'Best Actress', '7th Heaven'],
    ['Mary Pickford', 'Toronto', 'Canada', (1892, 4, 8), 1930, 'Best Actress', 'Coquette'],
    ['Norma Shearer', 'Montreal', 'Canada', (1902, 8, 10), 1930, 'Best Actress', 'The Divorcee'],
    ['Marie Dressler', 'Cobourg', 'Canada', (1868, 11, 2), 1931, 'Best Actress', 'Min and Bill'],
    ['Helen Hayes', 'Washington', 'USA', (1900, 10, 10), 1932, 'Best Actress', 'The Sin of Madelon Claudet'],
    ['Katharine Hepburn', 'Hartford', 'USA', (1907, 5, 12), 1934, 'Best Actress', 'Morning Glory'],
    ['Claudette Colbert', 'Paris', 'France', (1903, 9, 13), 1935, 'Best Actress', 'It Happened One Night'],
    ['Bette Davis', 'Lowell', 'USA', (1908, 4, 5), 1936, 'Best Actress', 'Dangerous'],
    ['Luise Rainer', 'Dusseldorf', 'Germany', (1910, 1, 12), 1937, 'Best Actress', 'The Great Ziegfeld'],
    ['Luise Rainer', 'Dusseldorf', 'Germany', (1910, 1, 12), 1938, 'Best Actress', 'The Good Earth'],
    ['Bette Davis', 'Lowell', 'USA', (1908, 4, 5), 1939, 'Best Actress', 'Jezebel'],
    ['Vivien Leigh', 'Darjeeling', 'India', (1913, 11, 5), 1940, 'Best Actress', 'Gone with the Wind'],
    ['Ginger Rogers', 'Independence', 'USA', (1911, 7, 16), 1941, 'Best Actress', 'Kitty Foyle'],
    ['Joan Fontaine', 'Tokyo', 'Japan', (1917, 10, 22), 1940, 'Best Actress', 'Suspicion'],
    ['Greer Garson', 'London', 'England', (1904, 9, 29), 1942, 'Best Actress', 'Mrs. Miniver'],
    ['Jennifer Jones', 'Tulsa', 'USA', (1919, 3, 2), 1944, 'Best Actress', 'The Song of Bernadette'],
    ['Ingrid Bergman', 'Stockholm', 'Sweden', (1915, 8, 29), 1945, 'Best Actress', 'Gaslight'],
    ['Joan Crawford', 'San Antonio', 'USA', (1905, 3, 23), 1946, 'Best Actress', 'Mildred Pierce'],
    ['Olivia de Havilland', 'Tokyo', 'Japan', (1916, 7, 1), 1947, 'Best Actress', 'To Each His Own'],
    ['Loretta Young', 'Salt Lake City', 'USA', (1913, 1, 6), 1948, 'Best Actress', "The Farmer's Daughter"],
    ['Jane Wyman', 'St. Joseph', 'USA', (1917, 1, 5), 1949, 'Best Actress', 'Johnny Belinda'],
    ['Olivia de Havilland', 'Tokyo', 'Japan', (1916, 7, 1), 1950, 'Best Actress', 'The Heiress'],
    ['Judy Holliday', 'New York City', 'USA', (1921, 6, 21), 1951, 'Best Actress', 'Born Yesterday'],
    ['Vivien Leigh', 'Darjeeling', 'India', (1913, 11, 5), 1952, 'Best Actress', 'A Streetcar Named Desire'],
    ['Shirley Booth', 'New York City', 'USA', (1898, 8, 30), 1953, 'Best Actress', 'Come Back, Little Sheba'],
    ['Audrey Hepburn', 'Brussels', 'Belgium', (1929, 5, 4), 1954, 'Best Actress', 'Roman Holiday'],
    ['Grace Kelly', 'Philadelphia', 'USA', (1929, 11, 12), 1955, 'Best Actress', 'The Country Girl'],
    ['Anna Magnani', 'Rome', 'Italy', (1908, 3, 7), 1956, 'Best Actress', 'The Rose Tattoo'],
    ['Ingrid Bergman', 'Stockholm', 'Sweden', (1915, 8, 29), 1957, 'Best Actress', 'Anastasia'],
    ['Joanne Woodward', 'Thomasville', 'USA', (1930, 2, 27), 1958, 'Best Actress', 'The Three Faces of Eve'],
    ['Susan Hayward', 'Brooklyn', 'USA', (1918, 6, 30), 1959, 'Best Actress', 'I Want To Live!'],
    ['Simone Signoret', 'Wiesbaden', 'Germany', (1921, 3, 25), 1960, 'Best Actress', 'Room at the Top'],
    ['Elizabeth Taylor', 'London', 'England', (1932, 2, 27), 1961, 'Best Actress', 'Butterfield 8'],
    ['Sophia Loren', 'Pozzuoli', 'Italy', (1934, 9, 20), 1962, 'Best Actress', 'Two Women'],
    ['Anne Bancroft', 'Bronx', 'USA', (1931, 9, 17), 1963, 'Best Actress', 'The Miracle Worker'],
    ['Patricia Neal', 'Packard', 'USA', (1926, 1, 20), 1964, 'Best Actress', 'Hud'],
    ['Julie Andrews', 'Walton-on-Thames', 'England', (1935, 10, 1), 1965, 'Best Actress', 'Mary Poppins'],
    ['Julie Christie', 'Chabua', 'India', (1941, 4, 14), 1966, 'Best Actress', 'Darling'],
    ['Elizabeth Taylor', 'London', 'England', (1932, 2, 27), 1967, 'Best Actress', "Who's Afraid of Virginia Woolf?"],
    ['Katharine Hepburn', 'Hartford', 'USA', (1907, 5, 12), 1968, 'Best Actress', "Guess Who's Coming to Dinner"],
    ['Barbra Streisand', 'Brooklyn', 'USA', (1942, 4, 24), 1969, 'Best Actress', 'Funny Girl'],
    ['Katharine Hepburn', 'Hartford', 'USA', (1907, 5, 12), 1969, 'Best Actress', 'The Lion in Winter'],
    ['Maggie Smith', 'Ilford', 'England', (1934, 12, 28), 1970, 'Best Actress', 'The Prime of Miss Jean Brodie'],
    ['Glenda Jackson', 'Birkenhead', 'England', (1936, 5, 9), 1971, 'Best Actress', 'Women in Love'],
    ['Jane Fonda', 'New York City', 'USA', (1937, 12, 21), 1972, 'Best Actress', 'Klute'],
    ['Liza Minnelli', 'Los Angeles', 'USA', (1946, 3, 12), 1973, 'Best Actress', 'Cabaret'],
    ['Glenda Jackson', 'Birkenhead', 'England', (1936, 5, 9), 1974, 'Best Actress', 'A Touch of Class'],
    ['Ellen Burstyn', 'Detroit', 'USA', (1932, 12, 7), 1975, 'Best Actress', "Alice Doesn't Live Here Anymore"],
    ['Louise Fletcher', 'Birmingham', 'USA', (1934, 7, 22), 1976, 'Best Actress', "One Flew Over the Cuckoo's Nest"],
    ['Faye Dunaway', 'Bascom', 'USA', (1941, 1, 14), 1977, 'Best Actress', 'Network'],
    ['Diane Keaton', 'Los Angeles', 'USA', (1946, 1, 5), 1978, 'Best Actress', 'Annie Hall'],
    ['Jane Fonda', 'New York City', 'USA', (1937, 12, 21), 1979, 'Best Actress', 'Coming Home'],
    ['Sally Field', 'Pasadena', 'USA', (1946, 11, 6), 1980, 'Best Actress', 'Norma Rae'],
    ['Sissy Spacek', 'Quitman', 'USA', (1949, 12, 25), 1981, 'Best Actress', "Coal Miner's Daughter"],
    ['Katharine Hepburn', 'Hartford', 'USA', (1907, 5, 12), 1982, 'Best Actress', 'On Golden Pond'],
    ['Meryl Streep', 'Summit', 'USA', (1949, 6, 22), 1983, 'Best Actress', "Sophie's Choice"],
    ['Shirley MacLaine', 'Richmond', 'USA', (1934, 4, 24), 1984, 'Best Actress', 'Terms of Endearment'],
    ['Sally Field', 'Pasadena', 'USA', (1946, 11, 6), 1985, 'Best Actress', 'Places in the Heart'],
    ['Geraldine Page', 'Kirksville', 'USA', (1924, 11, 22), 1986, 'Best Actress', 'The Trip to Bountiful'],
    ['Marlee Matlin', 'Morton Grove', 'USA', (1965, 8, 24), 1987, 'Best Actress', 'Children of a Lesser God'],
    ['Cher', 'El Centro', 'USA', (1946, 5, 20), 1988, 'Best Actress', 'Moonstruck'],
    ['Jodie Foster', 'Los Angeles', 'USA', (1962, 11, 19), 1989, 'Best Actress', 'The Accused'],
    ['Jessica Tandy', 'London', 'England', (1909, 6, 7), 1990, 'Best Actress', 'Driving Miss Daisy'],
    ['Kathy Bates', 'Memphis', 'USA', (1948, 6, 28), 1991, 'Best Actress', 'Misery'],
    ['Jodie Foster', 'Los Angeles', 'USA', (1962, 11, 19), 1992, 'Best Actress', 'The Silence of the Lambs'],
    ['Emma Thompson', 'London', 'England', (1959, 4, 15), 1993, 'Best Actress', 'Howards End'],
    ['Holly Hunter', 'Conyers', 'USA', (1958, 3, 20), 1994, 'Best Actress', 'The Piano'],
    ['Jessica Lange', 'Cloquet', 'USA', (1949, 4, 20), 1995, 'Best Actress', 'Blue Sky'],
    ['Susan Sarandon', 'Queens', 'USA', (1946, 10, 4), 1996, 'Best Actress', 'Dead Man Walking'],
    ['Frances McDormand', 'Chicago', 'USA', (1957, 6, 23), 1997, 'Best Actress', 'Fargo'],
    ['Helen Hunt', 'Culver City', 'USA', (1963, 6, 15), 1998, 'Best Actress', 'As Good As It Gets'],
    ['Gwyneth Paltrow', 'Los Angeles', 'USA', (1972, 9, 27), 1999, 'Best Actress', 'Shakespeare in Love'],
    ['Hilary Swank', 'Lincoln', 'USA', (1974, 7, 30), 2000, 'Best Actress', "Boys Don't Cry"],
    ['Julia Roberts', 'Smyrna', 'USA', (1967, 10, 28), 2001, 'Best Actress', 'Erin Brockovich'],
    ['Halle Berry', 'Cleveland', 'USA', (1966, 8, 14), 2002, 'Best Actress', "Monster's Ball"],
    ['Nicole Kidman', 'Honolulu', 'USA', (1967, 6, 20), 2003, 'Best Actress', 'The Hours'],
    ['Charlize Theron', 'Benoni', 'South Africa', (1975, 8, 7), 2004, 'Best Actress', 'Monster'],
    ['Hilary Swank', 'Lincoln', 'USA', (1974, 7, 30), 2005, 'Best Actress', 'Million Dollar Baby'],
    ['Reese Witherspoon', 'New Orleans', 'USA', (1976, 3, 22), 2006, 'Best Actress', 'Walk the Line'],
    ['Helen Mirren', 'Chiswick', 'England', (1945, 7, 26), 2007, 'Best Actress', 'The Queen'],
    ['Marion Cotillard', 'Paris', 'France', (1975, 9, 30), 2008, 'Best Actress', 'The Passionate Life of Edith Piaf'],
    ['Kate Winslet', 'Reading', 'England', (1975, 10, 5), 2009, 'Best Actress', 'The Reader'],
    ['Sandra Bullock', 'Arlington', 'USA', (1964, 7, 26), 2010, 'Best Actress', 'The Blind Side'],
    ['Natalie Portman', 'Jerusalem', 'Israel', (1981, 6, 9), 2011, 'Best Actress', 'Black Swan'],
    ['Meryl Streep', 'Summit', 'USA', (1949, 6, 22), 2012, 'Best Actress', 'The Iron Lady'],
    ['Jennifer Lawrence', 'Louisville', 'USA', (1990, 8, 15), 2013, 'Best Actress', 'Silver Linings Playbook'],
    ['Cate Blanchett', 'Melbourne', 'Australia', (1969, 5, 14), 2014, 'Best Actress', 'Blue Jasmine'],
    ['Gale Sondergaard', 'Litchfield', 'USA', (1899, 2, 15), 1937, 'Best Supporting Actress', 'Anthony Adverse'],
    ['Alice Brady', 'New York City', 'USA', (1892, 11, 2), 1938, 'Best Supporting Actress', 'In Old Chicago'],
    ['Fay Bainter', 'Los Angeles', 'USA', (1891, 12, 7), 1939, 'Best Supporting Actress', 'Jezebel'],
    ['Hattie McDaniel', 'Wichita', 'USA', (1893, 6, 10), 1940, 'Best Supporting Actress', 'Gone with the Wind'],
    ['Jane Darwell', 'Palmyra', 'USA', (1879, 10, 15), 1941, 'Best Supporting Actress', 'The Grapes of Wrath'],
    ['Mary Astor', 'Quincy', 'USA', (1906, 5, 3), 1942, 'Best Supporting Actress', 'The Great Lie'],
    ['Teresa Wright', 'New York City', 'USA', (1918, 10, 27), 1943, 'Best Supporting Actress', 'Mrs. Miniver'],
    ['Katina Paxinou', 'Athens', 'Greece', (1900, 12, 17), 1944, 'Best Supporting Actress', 'For Whom the Bell Tolls'],
    ['Ethel Barrymore', 'Philadelphia', 'USA', (1879, 8, 15), 1945, 'Best Supporting Actress',
     'None but the Lonely Heart'],
    ['Anne Revere', 'New York City', 'USA', (1903, 6, 25), 1946, 'Best Supporting Actress', 'National Velvet'],
    ['Anne Baxter', 'Michigan City', 'USA', (1923, 5, 7), 1947, 'Best Supporting Actress', "The Razor's Edge"],
    ['Celeste Holm', 'New York City', 'USA', (1917, 4, 29), 1948, 'Best Supporting Actress', "Gentleman's Agreement"],
    ['Claire Trevor', 'New York City', 'USA', (1910, 3, 8), 1949, 'Best Supporting Actress', 'Key Largo'],
    ['Mercedes McCambridge', 'Joliet', 'USA', (1916, 3, 17), 1950, 'Best Supporting Actress', "All the King's Men"],
    ['Josephine Hull', 'Newtonville', 'USA', (1886, 1, 3), 1951, 'Best Supporting Actress', 'Harvey'],
    ['Kim Hunter', 'Detroit', 'USA', (1922, 11, 12), 1952, 'Best Supporting Actress', 'A Streetcar Named Desire'],
    ['Gloria Grahame', 'Los Angeles', 'USA', (1923, 11, 28), 1953, 'Best Supporting Actress',
     'The Bad and the Beautiful'],
    ['Donna Reed', 'Denison', 'USA', (1921, 1, 27), 1954, 'Best Supporting Actress', 'From Here to Eternity'],
    ['Eva Marie Saint', 'Newark', 'USA', (1924, 7, 4), 1955, 'Best Supporting Actress', 'On the Waterfront'],
    ['Jo Van Fleet', 'Oakland', 'USA', (1914, 12, 30), 1956, 'Best Supporting Actress', 'East of Eden'],
    ['Dorothy Malone', 'Chicago', 'USA', (1925, 1, 30), 1957, 'Best Supporting Actress', 'Written on the Wind'],
    ['Miyoshi Umeki', 'Otaro', 'Japan', (1929, 4, 3), 1958, 'Best Supporting Actress', 'Sayonara'],
    ['Wendy Hiller', 'Bramhall', 'England', (1912, 8, 15), 1959, 'Best Supporting Actress', 'Separate Tables'],
    ['Shelley Winters', 'St. Louis', 'USA', (1920, 8, 18), 1960, 'Best Supporting Actress', 'The Diary of Anne Frank'],
    ['Shirley Jones', 'Charleroi', 'USA', (1934, 3, 31), 1961, 'Best Supporting Actress', 'Elmer Gantry'],
    ['Rita Moreno', 'Humacao', 'Puerto Rico', (1931, 12, 11), 1962, 'Best Supporting Actress', 'West Side Story'],
    ['Patty Duke', 'Elmhurst', 'USA', (1946, 12, 14), 1963, 'Best Supporting Actress', 'The Miracle Worker'],
    ['Margaret Rutherford', 'London', 'England', (1892, 5, 11), 1964, 'Best Supporting Actress', 'the V.I.P.s'],
    ['Lila Kedrova', 'St. Petersburg', 'Russia', (1918, 10, 9), 1965, 'Best Supporting Actress', 'Zorba the Greek'],
    ['Shelley Winters', 'St. Louis', 'USA', (1920, 8, 18), 1966, 'Best Supporting Actress', 'A Patch of Blue'],
    ['Sandy Dennis', 'Hastings', 'USA', (1937, 4, 27), 1967, 'Best Supporting Actress',
     "Who's Afraid of Virginia Woolf?"],
    ['Estelle Parsons', 'Marblehead', 'USA', (1927, 11, 20), 1968, 'Best Supporting Actress', 'Bonnie and Clyde'],
    ['Ruth Gordon', 'Quincy', 'USA', (1896, 10, 30), 1969, 'Best Supporting Actress', "Rosemary's Baby"],
    ['Goldie Hawn', 'Silver Spring', 'USA', (1945, 11, 21), 1970, 'Best Supporting Actress', 'Cactus Flower'],
    ['Helen Hayes', 'Washington', 'USA', (1900, 10, 10), 1971, 'Best Supporting Actress', 'Airport'],
    ['Cloris Leachman', 'Des Moines', 'USA', (1926, 4, 30), 1972, 'Best Supporting Actress', 'The Last Picture Show'],
    ['Eileen Heckart', 'Columbus', 'USA', (1919, 3, 29), 1973, 'Best Supporting Actress', 'Butterflies Are Free'],
    ["Tatum O'Neal", 'Los Angeles', 'USA', (1963, 11, 5), 1974, 'Best Supporting Actress', 'Paper Moon'],
    ['Ingrid Bergman', 'Stockholm', 'Sweden', (1915, 8, 29), 1975, 'Best Supporting Actress',
     'Murder on the Orient Express'],
    ['Lee Grant', 'New York City', 'USA', (1927, 10, 31), 1976, 'Best Supporting Actress', 'Shampoo'],
    ['Beatrice Straight', 'Old Westbury', 'USA', (1914, 8, 2), 1977, 'Best Supporting Actress', 'Network'],
    ['Vanessa Redgrave', 'London', 'England', (1937, 1, 30), 1978, 'Best Supporting Actress', 'Julia'],
    ['Maggie Smith', 'Ilford', 'England', (1934, 12, 28), 1979, 'Best Supporting Actress', 'California Suite'],
    ['Meryl Streep', 'Summit', 'USA', (1949, 6, 22), 1980, 'Best Supporting Actress', 'Kramer vs. Kramer'],
    ['Mary Steenburgen', 'Newport', 'USA', (1953, 2, 8), 1981, 'Best Supporting Actress', 'Melvin and Howard'],
    ['Maureen Stapleton', 'Troy', 'USA', (1925, 6, 21), 1982, 'Best Supporting Actress', 'Reds'],
    ['Jessica Lange', 'Cloquet', 'USA', (1949, 4, 20), 1983, 'Best Supporting Actress', 'Tootsie'],
    ['Linda Hunt', 'Morristown', 'USA', (1945, 4, 2), 1984, 'Best Supporting Actress',
     'The Year of Living Dangerously'],
    ['Peggy Ashcroft', 'Croydon', 'England', (1907, 12, 22), 1985, 'Best Supporting Actress', 'A Passage to India'],
    ['Anjelica Huston', 'Santa Monica', 'USA', (1951, 7, 8), 1986, 'Best Supporting Actress', "Prizzi's Honor"],
    ['Dianne Wiest', 'Kansas City', 'USA', (1948, 3, 28), 1987, 'Best Supporting Actress', 'Hannah and Her Sisters'],
    ['Olympia Dukakis', 'Lowell', 'USA', (1931, 6, 20), 1988, 'Best Supporting Actress', 'Moonstruck'],
    ['Geena Davis', 'Wareham', 'USA', (1956, 1, 21), 1989, 'Best Supporting Actress', 'The Accidental Tourist'],
    ['Brenda Fricker', 'Dublin', 'Ireland', (1945, 2, 17), 1990, 'Best Supporting Actress', 'My Left Foot'],
    ['Whoopi Goldberg', 'New York City', 'USA', (1955, 11, 13), 1991, 'Best Supporting Actress', 'Ghost'],
    ['Mercedes Ruehl', 'Queens', 'USA', (1948, 2, 28), 1992, 'Best Supporting Actress', 'The Fisher King'],
    ['Marisa Tomei', 'Brooklyn', 'USA', (1964, 12, 4), 1993, 'Best Supporting Actress', 'My Cousin Vinny'],
    ['Anna Paquin', 'Winnipeg', 'Canada', (1982, 7, 24), 1994, 'Best Supporting Actress', 'The Piano'],
    ['Dianne Wiest', 'Kansas City', 'USA', (1948, 3, 28), 1995, 'Best Supporting Actress', 'Bullets Over Broadway'],
    ['Mira Sorvino', 'Tenafly', 'USA', (1967, 9, 28), 1996, 'Best Supporting Actress', 'Mighty Aphrodite'],
    ['Juliette Binoche', 'Paris', 'France', (1964, 3, 9), 1997, 'Best Supporting Actress', 'The English Patient'],
    ['Kim Basinger', 'Athens', 'USA', (1953, 12, 8), 1998, 'Best Supporting Actress', 'L.A. Confidential'],
    ['Judi Dench', 'York', 'England', (1934, 12, 9), 1999, 'Best Supporting Actress', 'Shakespeare in Love'],
    ['Angelina Jolie', 'Los Angeles', 'USA', (1975, 6, 4), 2000, 'Best Supporting Actress', 'Girl, Interrupted'],
    ['Marcia Gay Harden', 'La Jolla', 'USA', (1959, 8, 14), 2001, 'Best Supporting Actress', 'Pollock'],
    ['Jennifer Connelly', 'Catskill Mountains', 'USA', (1970, 12, 12), 2002, 'Best Supporting Actress',
     'A Beautiful Mind'],
    ['Catherine Zeta-Jones', 'Mumbles', 'Wales', (1969, 9, 25), 2003, 'Best Supporting Actress', 'Chicago'],
    ['Renée Zellw', 'Katy', 'USA', (1969, 4, 25), 2004, 'Best Supporting Actress', 'Cold Mountain'],
    ['Cate Blanchett', 'Melbourne', 'Australia', (1969, 5, 14), 2005, 'Best Supporting Actress', 'The Aviator'],
    ['Rachel Weisz', 'London', 'England', (1971, 3, 7), 2006, 'Best Supporting Actress', 'The Constant Gardener'],
    ['Jennifer Hudson', 'Chicago', 'USA', (1981, 9, 12), 2007, 'Best Supporting Actress', 'Dreamgirls'],
    ['Tilda Swinton', 'London', 'England', (1960, 11, 5), 2007, 'Best Supporting Actress', 'Michael Clayton'],
    ['Penelope Cruz', 'Madrid', 'Spain', (1974, 4, 28), 2009, 'Best Supporting Actress', 'Vicky Cristina Barcelona'],
    ["Mo'Nique", 'Woodlawn', 'USA', (1967, 12, 11), 2010, 'Best Supporting Actress', 'Precious'],
    ['Melissa Leo', 'New York City', 'USA', (1960, 9, 14), 2011, 'Best Supporting Actress', 'The Fighter'],
    ['Octavia Spencer', 'Montgomery', 'USA', (1972, 5, 25), 2012, 'Best Supporting Actress', 'The Help'],
    ['Anne Hathaway', 'Brooklyn', 'USA', (1982, 11, 12), 2013, 'Best Supporting Actress', 'Les Misérables'],
    ["Lupita Nyong'o", 'Mexico City', 'Mexico', (1983, 3, 1), 2014, 'Best Supporting Actress', '12 Years a Slave'],
    ['Billy Wilder', 'Sucha', 'Austria', (1906, 6, 22), 1961, 'Best Director', 'The Apartment'],
    ['Ginger Rogers', 'Independence', 'USA', (1911, 7, 16), 1941, 'Best Actress', 'Kitty Foyle'],
    ['Tom Hanks', 'Concord', 'USA', (1956, 7, 9), 1994, 'Best Actor', 'Philadelphia'],
    ['Michael Cimino', 'New York City', 'USA', (1939, 2, 3), 1979, 'Best Director', 'The Deer Hunter'],
    ['Mary Astor', 'Quincy', 'USA', (1906, 5, 3), 1942, 'Best Supporting Actress', 'The Great Lie'],
    ['Angelina Jolie', 'Los Angeles', 'USA', (1975, 6, 4), 2000, 'Best Supporting Actress', 'Girl, Interrupted'],
    ['Lee Grant', 'New York City', 'USA', (1927, 10, 31), 1976, 'Best Supporting Actress', 'Shampoo'],
    ['Anne Revere', 'New York City', 'USA', (1903, 6, 25), 1946, 'Best Supporting Actress', 'National Velvet'],
    ['Faye Dunaway', 'Bascom', 'USA', (1941, 1, 14), 1977, 'Best Actress', 'Network'],
    ['Van Heflin', 'Walters', 'USA', (1910, 12, 13), 1943, 'Best Supporting Actor', 'Johnny Eager'],
    ['Joanne Woodward', 'Thomasville', 'USA', (1930, 2, 27), 1958, 'Best Actress', 'The Three Faces of Eve'],
    ['Gary Cooper', 'Helena', 'USA', (1901, 5, 7), 1953, 'Best Actor', 'High Noon'],
    ['Elizabeth Taylor', 'London', 'England', (1932, 2, 27), 1967, 'Best Actress', "Who's Afraid of Virginia Woolf?"],
    ['Hilary Swank', 'Lincoln', 'USA', (1974, 7, 30), 2005, 'Best Actress', 'Million Dollar Baby'],
    ['Hilary Swank', 'Lincoln', 'USA', (1974, 7, 30), 2005, 'Best Actress', 'Million Dollar Baby'],
    ['Gwyneth Paltrow', 'Los Angeles', 'USA', (1972, 9, 27), 1999, 'Best Actress', 'Shakespeare in Love'],
    ['Jack Albertson', 'Malden', 'USA', (1907, 6, 16), 1969, 'Best Supporting Actor', 'The Subject Was Roses'],
    ["Mo'Nique", 'Woodlawn', 'USA', (1967, 12, 11), 2010, 'Best Supporting Actress', 'Precious'],
    ['Marcia Gay Harden', 'La Jolla', 'USA', (1959, 8, 14), 2001, 'Best Supporting Actress', 'Pollock'],
    ['Maggie Smith', 'Ilford', 'England', (1934, 12, 28), 1970, 'Best Actress', 'The Prime of Miss Jean Brodie'],
    ['Rachel Weisz', 'London', 'England', (1971, 3, 7), 2006, 'Best Supporting Actress', 'The Constant Gardener'],
    ['Danny Boyle', 'Manchester', 'England', (1956, 10, 20), 2009, 'Best Director', 'Slumdog Millionaire'],
    ['Jason Robards', 'Chicago', 'USA', (1922, 7, 26), 1977, 'Best Supporting Actor', "All the President's Men"],
    ['James Coburn', 'Laurel', 'USA', (1928, 8, 31), 1999, 'Best Supporting Actor', 'Affliction'],
    ['John Huston', 'Nevada', 'USA', (1906, 8, 5), 1949, 'Best Director', 'The Treasure of the Sierra Madre']
]

NAJSTAREJSI = [
    [(PODATKI_TEST_1,), 'Frank Lloyd'],
    [(PODATKI_TEST_2[:20],), 'Victor Fleming'],
    [(PODATKI_TEST_2,), 'George Arliss']
]

PO_DRZAVAH = [
    [(PODATKI_TEST_1,), {'Moldova': 2, 'Scotland': 1}],
    [(PODATKI_TEST_2,), {'Moldova': 2,
                         'Scotland': 3, 'USA': 293, 'Italy': 7, 'France': 9, 'Hungary': 2, 'Austria': 7, 'Turkey': 2,
                         'England': 57, 'Germany': 4, 'Japan': 5, 'Canada': 8, 'New Zealand': 2, 'Taiwan': 2,
                         'Switzerland': 1, 'Ukraine': 1, 'Wales': 6, 'Puerto Rico': 3, 'Russia': 3, 'Australia': 4,
                         'Ireland': 2, 'Mexico': 3, 'Romania': 1, 'Cambodia': 1, 'Canary Islands': 1, 'India': 3,
                         'Sweden': 3, 'Belgium': 1, 'South Africa': 1, 'Israel': 1, 'Greece': 1, 'Spain': 1}]
]

V_DRZAVI = [
    [([['Janez McTiernan', 'Ljubljana', 'Slovenia', (1990, 9, 30), 2010, 'Best Director', 'Code hard 2'],
       ['Branko Vilič', 'Maribor', 'Slovenia', (1970, 1, 21), 2010, 'Best Actor', 'Code hard 2'],
       ['Julija Rebernik', 'Celje', 'Slovenia', (1986, 2, 2), 2012, 'Best Actor', 'Eat, pray, code']],
      'Slovenia', (1990, 2020)), {'Branko Vilič', 'Janez McTiernan', 'Julija Rebernik'}],
    [(PODATKI_TEST_2, "USA", (1990, 1995)), {'Al Pacino', 'Clint Eastwood', 'Denzel Washington',
                                             'Dianne Wiest', 'Gene Hackman', 'Holly Hunter', 'Jack Palance',
                                             'Jessica Lange', 'Jodie Foster', 'Joe Pesci', 'Jonathan Demme',
                                             'Kathy Bates', 'Kevin Costner', 'Marisa Tomei', 'Martin Landau',
                                             'Mercedes Ruehl', 'Oliver Stone', 'Robert Zemeckis', 'Steven Spielberg',
                                             'Tom Hanks', 'Tommy Lee Jones', 'Whoopi Goldberg'}],
    [(PODATKI_TEST_2, "France", (1000, 3000)), {'Claudette Colbert', 'Jean Dujardin', 'William Wyler',
                                                'Michel Hazanavicius', 'Marion Cotillard', 'Roman Polanski',
                                                'Juliette Binoche'}],
]

SKUPNI = [
    [([['Branko Vilič', 'Maribor', 'Slovenia', (1970, 1, 21), 2009, 'Best Actor', 'Code hard 1'],
       ['Janez McTiernan', 'Ljubljana', 'Slovenia', (1990, 9, 30), 2009, 'Best Director', 'Code hard 1'],
       ['Janez McTiernan', 'Ljubljana', 'Slovenia', (1990, 9, 30), 2010, 'Best Director', 'Code hard 2'],
       ['Branko Vilič', 'Maribor', 'Slovenia', (1970, 1, 21), 2010, 'Best Actor', 'Code hard 2'],
       ['Julija Rebernik', 'Celje', 'Slovenia', (1986, 2, 2), 2012, 'Best Actor', 'Eat, pray, code']],),
     {('Branko Vilič', 'Janez McTiernan'): {'Code hard 1', 'Code hard 2'}}],
    [(PODATKI_TEST_2[:100],), {('John Ford', 'Victor McLaglen'): {'The Informer'},
                               ('Jerome Robbins', 'Robert Wise'): {'West Side Story'},
                               ('Ethan Coen', 'Joel Coen'): {'No Country for Old Men'},
                               ('Clark Gable', 'Frank Capra'): {'It Happened One Night'}}],
    [(PODATKI_TEST_2,), {('Frank Capra', 'Clark Gable'): {'It Happened One Night'},
                         ('Frank Capra', 'Claudette Colbert'): {'It Happened One Night'},
                         ('John Ford', 'Victor McLaglen'): {'The Informer'},
                         ('Victor Fleming', 'Vivien Leigh'): {'Gone with the Wind'},
                         ('Victor Fleming', 'Hattie McDaniel'): {'Gone with the Wind'},
                         ('John Ford', 'Jane Darwell'): {'The Grapes of Wrath'},
                         ('John Ford', 'Donald Crisp'): {'How Green Was My Valley'},
                         ('William Wyler', 'Greer Garson'): {'Mrs. Miniver'},
                         ('William Wyler', 'Teresa Wright'): {'Mrs. Miniver'},
                         ('Leo McCarey', 'Bing Crosby'): {'Going My Way'},
                         ('Leo McCarey', 'Barry Fitzgerald'): {'Going My Way'},
                         ('Jerome Robbins', 'Robert Wise'): {'West Side Story'},
                         ('Jerome Robbins', 'George Chakiris'): {'West Side Story'},
                         ('Jerome Robbins', 'Rita Moreno'): {'West Side Story'},
                         ('Billy Wilder', 'Ray Milland'): {'The Lost Weekend'},
                         ('William Wyler', 'Fredric March'): {'The Best Years of Our Lives'},
                         ('William Wyler', 'Harold Russell'): {'The Best Years of Our Lives'},
                         ('Elia Kazan', 'Celeste Holm'): {"Gentleman's Agreement"},
                         ('John Huston', 'Walter Huston'): {'The Treasure of the Sierra Madre'},
                         ('Joseph L. Mankiewicz', 'George Sanders'): {'All About Eve'},
                         ('Fred Zinnemann', 'Frank Sinatra'): {'From Here to Eternity'},
                         ('Fred Zinnemann', 'Donna Reed'): {'From Here to Eternity'},
                         ('Elia Kazan', 'Marlon Brando'): {'On the Waterfront'},
                         ('Elia Kazan', 'Eva Marie Saint'): {'On the Waterfront'},
                         ('Delbert Mann', 'Ernest Borgnine'): {'Marty'},
                         ('David Lean', 'Alec Guinness'): {'The Bridge on the River Kwai'},
                         ('William Wyler', 'Hugh Griffith'): {'Ben-Hur'},
                         ('Robert Wise', 'George Chakiris'): {'West Side Story'},
                         ('Robert Wise', 'Rita Moreno'): {'West Side Story'},
                         ('George Cukor', 'Rex Harrison'): {'My Fair Lady'},
                         ('Joel Coen', 'Ethan Coen'): {'No Country for Old Men'},
                         ('Joel Coen', 'Javier Bardem'): {'No Country for Old Men'},
                         ('Franklin J. Schaffner', 'George C. Scott'): {'Patton'},
                         ('William Friedkin', 'Gene Hackman'): {'The French Connection'},
                         ('Bob Fosse', 'Joel Grey'): {'Cabaret'}, ('Bob Fosse', 'Liza Minnelli'): {'Cabaret'},
                         ('Francis Ford Coppola', 'Robert De Niro'): {'The Godfather Part II'},
                         ('Woody Allen', 'Diane Keaton'): {'Annie Hall'},
                         ('Michael Cimino', 'Christopher Walken'): {'The Deer Hunter'},
                         ('Robert Benton', 'Dustin Hoffman'): {'Kramer vs. Kramer'},
                         ('Robert Benton', 'Meryl Streep'): {'Kramer vs. Kramer'},
                         ('Warren Beatty', 'Maureen Stapleton'): {'Reds'},
                         ('Richard Attenborough', 'Ben Kingsley'): {'Gandhi'},
                         ('James L. Brooks', 'Jack Nicholson'): {'Terms of Endearment'},
                         ('James L. Brooks', 'Shirley MacLaine'): {'Terms of Endearment'},
                         ('Milos Forman', 'F. Murray Abraham'): {'Amadeus'},
                         ('Jonathan Demme', 'Jodie Foster'): {'The Silence of the Lambs'},
                         ('Clint Eastwood', 'Gene Hackman'): {'Unforgiven'},
                         ('Robert Zemeckis', 'Tom Hanks'): {'Forrest Gump'},
                         ('Anthony Minghella', 'Juliette Binoche'): {'The English Patient'},
                         ('Sam Mendes', 'Kevin Spacey'): {'American Beauty'},
                         ('Steven Soderbergh', 'Benicio Del Toro'): {'Traffic'},
                         ('Ron Howard', 'Jennifer Connelly'): {'A Beautiful Mind'},
                         ('Roman Polanski', 'Adrien Brody'): {'The Pianist'},
                         ('Clint Eastwood', 'Morgan Freeman'): {'Million Dollar Baby'},
                         ('Clint Eastwood', 'Hilary Swank'): {'Million Dollar Baby'},
                         ('Ethan Coen', 'Javier Bardem'): {'No Country for Old Men'},
                         ('Michel Hazanavicius', 'Jean Dujardin'): {'The Artist'},
                         ('Clark Gable', 'Claudette Colbert'): {'It Happened One Night'},
                         ('Bing Crosby', 'Barry Fitzgerald'): {'Going My Way'},
                         ('Fredric March', 'Harold Russell'): {'The Best Years of Our Lives'},
                         ('Marlon Brando', 'Eva Marie Saint'): {'On the Waterfront'},
                         ('David Niven', 'Wendy Hiller'): {'Separate Tables'},
                         ('Burt Lancaster', 'Shirley Jones'): {'Elmer Gantry'},
                         ('Jack Nicholson', 'Louise Fletcher'): {"One Flew Over the Cuckoo's Nest"},
                         ('Peter Finch', 'Faye Dunaway'): {'Network'},
                         ('Peter Finch', 'Beatrice Straight'): {'Network'},
                         ('Jon Voight', 'Jane Fonda'): {'Coming Home'},
                         ('Dustin Hoffman', 'Meryl Streep'): {'Kramer vs. Kramer'},
                         ('Henry Fonda', 'Katharine Hepburn'): {'On Golden Pond'},
                         ('Daniel Day-Lewis', 'Brenda Fricker'): {'My Left Foot'},
                         ('Sean Penn', 'Tim Robbins'): {'Mystic River'},
                         ('Matthew McConaughey', 'Jared Leto'): {'Dallas Buyers Club'},
                         ('Karl Malden', 'Vivien Leigh'): {'A Streetcar Named Desire'},
                         ('Karl Malden', 'Kim Hunter'): {'A Streetcar Named Desire'},
                         ('Frank Sinatra', 'Donna Reed'): {'From Here to Eternity'},
                         ('Red Buttons', 'Miyoshi Umeki'): {'Sayonara'},
                         ('George Chakiris', 'Rita Moreno'): {'West Side Story'},
                         ('Melvyn Douglas', 'Patricia Neal'): {'Hud'},
                         ('Ben Johnson', 'Cloris Leachman'): {'The Last Picture Show'},
                         ('Joel Grey', 'Liza Minnelli'): {'Cabaret'}, ('Jason Robards', 'Vanessa Redgrave'): {'Julia'},
                         ('Jack Nicholson', 'Shirley MacLaine'): {'Terms of Endearment'},
                         ('Michael Caine', 'Dianne Wiest'): {'Hannah and Her Sisters'},
                         ('Morgan Freeman', 'Hilary Swank'): {'Million Dollar Baby'},
                         ('Christian Bale', 'Melissa Leo'): {'The Fighter'},
                         ('Bette Davis', 'Fay Bainter'): {'Jezebel'},
                         ('Vivien Leigh', 'Hattie McDaniel'): {'Gone with the Wind'},
                         ('Greer Garson', 'Teresa Wright'): {'Mrs. Miniver'},
                         ('Vivien Leigh', 'Kim Hunter'): {'A Streetcar Named Desire'},
                         ('Anne Bancroft', 'Patty Duke'): {'The Miracle Worker'},
                         ('Elizabeth Taylor', 'Sandy Dennis'): {"Who's Afraid of Virginia Woolf?"},
                         ('Faye Dunaway', 'Beatrice Straight'): {'Network'},
                         ('Cher', 'Olympia Dukakis'): {'Moonstruck'}, ('Holly Hunter', 'Anna Paquin'): {'The Piano'},
                         ('Gwyneth Paltrow', 'Judi Dench'): {'Shakespeare in Love'}
                         }],
]
